### PR TITLE
dependabot: Get updates batched together weekly

### PR DESCRIPTION
**Pull request by russellb**
83b9857 dependabot: Get updates batched together weekly

commit 83b98571b7c89685653f05f0b464c9745e61521e
Author: Russell Bryant <rbryant@redhat.com>
Date:   Mon Jun 17 18:14:58 2024 -0400

    dependabot: Get updates batched together weekly
    
    If there are multiple updates for a given ecosystem, include them in a
    single PR once a week.
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

### CODE REVIEW

**Comment by drpaneas** [comment]
out of curiosity, what was the issue with `daily`?

/lgtm

**Comment by russellb** [comment]
> out of curiosity, what was the issue with `daily`?
> 
> /lgtm

just noisy - personal opinion, I guess.

seeing updates come in per dependency across 10+ repos every day started to annoy me :-)

**Review by nathan-weinberg — COMMENTED** [review]
I like the idea of less notifications but I also like being able to test/revert individual version bumps

**Comment by drpaneas** [comment]
I think it will still show you distinct commits, and latthener it depends if you want to "Squash and merge".

**Comment by bjhargrave** [comment]
I am still not sure the velocity of dependabot PRs warrants this. Also if a PR has multiple changes and one of them is an issue for us, we will not be able to tell which one since the whole PR will fail. Distinct PRs allows us to identify if an individual dependency change is a problem.

**Comment by bjhargrave** [comment]
> seeing updates come in per dependency across 10+ repos every day started to annoy me :-)

This wont fix that since each repo must have its own PRs.

**Comment by russellb** [comment]
> If we get into a weekly cadence, do we still get distinct commits or is it a single commit with all the dep bumps? If multiple commits then LGTM!

single commit

> > seeing updates come in per dependency across 10+ repos every day started to annoy me :-)
> 
> This wont fix that since each repo must have its own PRs.

but it's at least once a week!

**Comment by russellb** [comment]
there's not clear consensus on this so I'll close

my personal annoyance isn't quite enough justification to push it ;-)

**Pull request closed without merging**
