### PR TITLE
Add libaio-dev to the e2e runner for async_io

### PR DESCRIPTION
**Pull request by nerdalert**
Resolves the inference warning messages on cuda nodes. Here are the original errors which you can view in e2e action / Run e2e test job:

```
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
```

Those are resolved once ` libaio-dev` is installed. Fedora displays the same but I haven't figured out the right incantation to get the order of operations fixed with it yet as I'm still putting together a fedora workflow on external runners. I've tested the change on external GH runners  if you want to view the results [here](https://github.com/nerdalert/ilab-runner/actions/runs/9728373090/job/26849057557). Ty.

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by tiran** [comment]
Please update `docs/gpu-acceleration.md`, too.

**Review by leseb — COMMENTED** [review]
It'd be great to incorporate all the PR description into the commit message as well.

**Comment by nathan-weinberg** [comment]
@nerdalert feel free to remove the `hold` label once it's sorted!

**Comment by nathan-weinberg** [comment]
@nerdalert the `e2e.yml` job was removed in https://github.com/instructlab/instructlab/pull/1651 - if you want I'd welcome updating this for the equivalent `e2e` AWS-based jobs

**Comment by nathan-weinberg** [comment]
PR seems abandoned and the E2E ecosystem has changed quite a bit since this was opened - closing this.

**Pull request closed without merging**
