### PR TITLE
add examples how to use non-default models to serve/chat/generate

### LINKED ISSUE #1357: [doc] Issue of generating data use larger model in TROUBLESHOOTING.md
In [TROUBLESHOOTING.md](https://github.com/instructlab/instructlab/blob/main/TROUBLESHOOTING.md#how-to-improve-the-quality-of-generated-data) , it said user can use ' --model'  to use better models. But this parameter is not used to specify llm used to generate(see #1230 ). Currently, the only way is first serve a model by 'ilab serve ...' , then run 'ilab generate --endpoint-url ...'.

```
3. Using a better model via --model Larger models can lead to better data generation. This option requires users to be familiar with various existing models, and which specific models would suit their needs. This could mean either using a model with more nodes than the default InstructLab merlinite-7b-lab model, such as the Mixtral-8x7B-Instruct-v0.1 model, or using an unquantized version of the InstructLab merlinite-7b-lab model. It can be used as follows: ilab generate --model Mixtral-8x7B-Instruct-v0.1'

```

### PR DESCRIPTION
**Pull request by chudegao**
Many users are seeking ways to use a larger model(e.g. mixtral) to generate data, currently there's no examples how to use a non-default models to serve/chat/generate and the command line help message is not clear enough.  This PR add some examples and makes it more clear.

**Issue resolved by this Pull Request:**
Resolves #1357

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by leseb — COMMENTED** [review]
Thanks for adding more documentation! Please take a look at the CI failure on markdown. Thanks!

**Review by leseb — CHANGES_REQUESTED** [review]
Please update your commit message with the content of PR description, thanks!

**Comment by chudegao** [comment]
> Please update your commit message with the content of PR description, thanks!

updated

**Review by leseb — APPROVED** [review]

**Review by tiran — APPROVED** [review]
LGTM

README.md already has an example for `ilab download` of mixtral

**Pull request merged**
