### PR TITLE
fix: Bring 'taxonomy diff' validation in line with 'data generate'

### LINKED ISSUE #1911: inconsistent error handling between ilab taxonomy diff and ilab data generate
From ilab taxonomy diff:
`Taxonomy in /home/bcrochet/.local/share/instructlab/taxonomy is valid :)`
From ilab data generate:
`ERROR 2024-07-29 12:45:01,886 instructlab.sdg.utils.taxonomy:207: Version 2 is not supported for knowledge taxonomy. Minimum supported version is 3.`
ilab taxonomy diff should throw the same errors as ilab data generate or pick one to be consistent across both

### PR DESCRIPTION
**Pull request by bcrochet**
There is a divergence between how the SDG library does validation and the 'taxonomy diff' command does the validation of the taxonomy. This brings it in line.

Resolves #1911 

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [x] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [x] Unit tests have been added, if necessary.
- [x] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by nathan-weinberg** [comment]
Apart from `mypy` error LGTM @bcrochet :+1:

**Comment by bcrochet** [comment]
> Apart from `mypy` error LGTM @bcrochet :+1: 

Fixed.

**Review by nathan-weinberg — APPROVED** [review]

**Review by markmc — APPROVED** [review]
lgtm, thanks @bcrochet

**Pull request merged**
