### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jjasghar**
python3 defaults to python3.9 if you don't specify 3.11.

### CODE REVIEW

**Comment by bjhargrave** [comment]
> python3 defaults to python3.9

I think it depends upon how one's system is setup:

```shell
➜  ~ python3 --version
Python 3.12.5
```

But just using python3 is not specific enough since we now require with 3.10 or 3.11.

**Comment by danmcp** [comment]
Maybe we should instead add a comment to explain what python3 needs to be (or to use python3.10 or python3.11 if desired).

**Review by danmcp — CHANGES_REQUESTED** [review]
Maybe we should instead add a comment to explain what python3 needs to be (or to use python3.10 or python3.11 if desired).

**Comment by nathan-weinberg** [comment]
Superceded by https://github.com/instructlab/instructlab/pull/2226

**Pull request closed without merging**
