### PR TITLE
add hostname, python version and capabilities definition to system info output

### PR DESCRIPTION
**Pull request by jeremyeder**
Added small improvements and clarifications to ilab system info output

### CODE REVIEW

**Comment by nathan-weinberg** [comment]
@jeremyeder can you update the PR description/commit message to more accurately reflect the changes?

**Review by RobotSail — APPROVED** [review]
LGTM

**Review by JamesKunstle — COMMENTED** [review]
Changes are good- just need to fix linting and add a small description to commit.

can lint with `make fix`

**Comment by nathan-weinberg** [comment]
Thanks @jeremyeder - once linting errors are fixed this LGTM

**Review by nathan-weinberg — APPROVED** [review]

**Pull request merged**
