### PR TITLE
fix: use all prompts in a batch to generate data

### LINKED ISSUE #1292: ilab generate batch issue
**Describe the bug**
In function openai_completion()(https://github.com/instructlab/instructlab/blob/main/src/instructlab/generator/utils.py), it should call llm with all prompts(a batch with 5 prompts), however ,the implementation seems only use the first prompt.

image
image

in line 105: prompt_batches will be a list of list(1*5): [[prompt1, prompt2, prompt3, prompt4, prompt5]]
in line 111: it will enumerate prompt_batches, only once as it only has one element, so batch_id is 0.
in line 152, it only use prompt_batch[batch_id](actually is prompt_batches[0][0]), not enumerate all 5 prompt in prompt_batch(prompt_batches[0]) to use.

openai chat api client.chat.completions.create() does not support batch, so for a batch prompts in prompt_batch need an extra loop to call the api. 

**To Reproduce**
I found the issue by reading the code.

**Expected behavior**
all seed prompts in a batch should be used to call llm to generate data

### PR DESCRIPTION
**Pull request by chudegao**
Cnhance the code logic to use all batch prompts when call LLM api.

**Issue resolved by this Pull Request:**
Resolves #1292

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by leseb — COMMENTED** [review]
Could you please clarify (in the commit message), what issue this is solving or what enhancement it is providing?
The code seems ok to me, what I'm missing is the context.

Thanks!

**Comment by chudegao** [comment]
> Could you please clarify (in the commit message), what issue this is solving or what enhancement it is providing? The code seems ok to me, what I'm missing is the context.
> 
> Thanks!

Updated the commit message.
The issue and details are in https://github.com/instructlab/instructlab/issues/1292  . The original code in openai_completion() only use the first prompt and missed last 4 of a batch(5) prompts. The fix is adding an extra loop to use all 5 prompts to call llm(openai chat completion api) to generate data. 
```
for batch_id, prompt_batch in enumerate(prompt_batches):
    ....
    messages = [
                {"role": "system", "content": get_sysprompt()},
                {"role": "user", "content": prompt_batch[batch_id]},   =====>> here's the issue as prompt_batch is a list of 5 prompts
            ]
```

**Review by leseb — COMMENTED** [review]
Thanks for clarifying! I’m curious if the decision to use a single prompt was intentional, as I feel I might be missing some context here. @chudegao, could you explain the benefits of using multiple prompts compared to the current approach? Thanks! Just to be clear the code LGTM, it's just the impact of the change that I'm still missing.

**Comment by chudegao** [comment]
> Thanks for clarifying! I’m curious if the decision to use a single prompt was intentional, as I feel I might be missing some context here. @chudegao, could you explain the benefits of using multiple prompts compared to the current approach? Thanks! Just to be clear the code LGTM, it's just the impact of the change that I'm still missing.

@markstur can you help confirm?

**Review by russellb — CHANGES_REQUESTED** [review]
This code was moved over to the `instructlab/sdg` repo. Can you propose a change there?  Thanks!

**Comment by chudegao** [comment]
> This code was moved over to the `instructlab/sdg` repo. Can you propose a change there? Thanks!

Ok

**Comment by leseb** [comment]
Closing based on https://github.com/instructlab/instructlab/pull/1311#issuecomment-2177955894. Looking forward to your PR in `instructlab/sdg`. Thanks!

**Pull request closed without merging**
