### PR TITLE
fix: report server errors for chat/generate/eval

### PR DESCRIPTION
**Pull request by leseb**
When the internal server crashes, the errors will be displayed in the chat, as well as the progress logs from generate and other related commands.

Fixes: https://github.com/instructlab/instructlab/issues/889

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Functional tests have been added, if nessessary.
- [ ] E2E Workflow tests have been added, if necessary.

### CODE REVIEW

**Review by danmcp — COMMENTED** [review]
Couple questions:

- Is there a recommended way to test? I tried killing the serving process but it didn't behave any differently than before
- How should we think about this change relative to the behavior with vllm?

**Comment by leseb** [comment]
> Couple questions:
> 
> * Is there a recommended way to test? I tried killing the serving process but it didn't behave any differently than before

The best way is to do what the func test used to do to validate stderr is not surfaced. So essentially:

```bash
ilab model chat
<start chatting>
<send ctrl+C during a response>
<llama-cpp prints 'disconnected' in the chat
```

> * How should we think about this change relative to the behavior with vllm?
We would need to revert this https://github.com/instructlab/instructlab/commit/b4a1af5c6a93cff598bde854663f798bb863176b, but it might cause other issues :/

**Comment by danmcp** [comment]
> > * How should we think about this change relative to the behavior with vllm?
> 
> We would need to revert this [b4a1af5](https://github.com/instructlab/instructlab/commit/b4a1af5c6a93cff598bde854663f798bb863176b), but it might cause other issues :/

Not following.  We would want to revert that change so the logging output wouldn't show up in chat?  Isn't vllm is pretty chatting even without logging enabled?

**Comment by danmcp** [comment]
> > > > * How should we think about this change relative to the behavior with vllm?
> > > 
> > > 
> > > We would need to revert this [b4a1af5](https://github.com/instructlab/instructlab/commit/b4a1af5c6a93cff598bde854663f798bb863176b), but it might cause other issues :/
> > 
> > 
> > Not following. We would want to revert that change so the logging output wouldn't show up in chat? Isn't vllm is pretty chatting even without logging enabled?
> 
> We would want to revert this to show the server's internal errors to the chat window yes. vLLM is outputting to stdout/stderr, right?

If not set to background, it will output stdout/err.  Currently it's set to background for chat.  If we didn't do that, we would get a constant stream of messages from vllm in the chat.  If logging is enabled (we are accepting the default of enabled with the change you referenced), it will be even more chatty.  But I don't see how the logging being enabled or not changes the decision.  In either case I don't see how we can let all the vllm output flow to console.

Just a note regarding the logging being enabled.  The reason we have that logic in place is because vllm logging wrecks havoc on instructlab logging when imported through lm_eval.  So we have to disable it for instructlab, but we accept the default when launching vllm.

General thoughts about this change:
- It's probably fine given how llamacpp behaves (doesn't seem to output anything but errors).
- Not possible with the current impl of vllm.  We would need to suppress everything but errors.
- Don't love that we are going to have completely different behaviors between the two
- Wondering whether there is another change that could be made consistently to only show the serving output (or a tail of the output) when a failure occurred.

**Comment by leseb** [comment]
> > > > > * How should we think about this change relative to the behavior with vllm?
> > > > 
> > > > 
> > > > We would need to revert this [b4a1af5](https://github.com/instructlab/instructlab/commit/b4a1af5c6a93cff598bde854663f798bb863176b), but it might cause other issues :/
> > > 
> > > 
> > > Not following. We would want to revert that change so the logging output wouldn't show up in chat? Isn't vllm is pretty chatting even without logging enabled?
> > 
> > 
> > We would want to revert this to show the server's internal errors to the chat window yes. vLLM is outputting to stdout/stderr, right?
> 
> If not set to background, it will output stdout/err. Currently it's set to background for chat. If we didn't do that, we would get a constant stream of messages from vllm in the chat. If logging is enabled (we are accepting the default of enabled with the change you referenced), it will be even more chatty. But I don't see how the logging being enabled or not changes the decision. In either case I don't see how we can let all the vllm output flow to console.
> 
> Just a note regarding the logging being enabled. The reason we have that logic in place is because vllm logging wrecks havoc on instructlab logging when imported through lm_eval. So we have to disable it for instructlab, but we accept the default when launching vllm.
> 
> General thoughts about this change:
> 
> * It's probably fine given how llamacpp behaves (doesn't seem to output anything but errors).
> * Not possible with the current impl of vllm.  We would need to suppress everything but errors.
> * Don't love that we are going to have completely different behaviors between the two
> * Wondering whether there is another change that could be made consistently to only show the serving output (or a tail of the output) when a failure occurred.

Thanks for the analysis. In conclusion, I believe we can move forward with this, right? Thanks!

**Comment by danmcp** [comment]
> Thanks for the analysis. In conclusion, I believe we can move forward with this, right? Thanks!

If my understanding is correct (I put it out there to make sure I was following the change and current state correctly), I don't object to this change going in.

**Comment by leseb** [comment]
> > Thanks for the analysis. In conclusion, I believe we can move forward with this, right? Thanks!
> 
> If my understanding is correct (I put it out there to make sure I was following the change and current state correctly), I don't object to this change going in.

It is correct :)

**Review by danmcp — APPROVED** [review]

**Review by nathan-weinberg — APPROVED** [review]

**Pull request merged**
