### PR TITLE
chore: remove stale jupyter notebooks

### PR DESCRIPTION
**Pull request by alimaredia**
The training used on juptyr notebooks is the
legacy training and do not work with the data
generated anymore.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by jaideepr97** [comment]
@alimaredia please remove the notebook validation from the CI config as well

**Review by jaideepr97 — COMMENTED** [review]
@alimaredia please remove the notebook validation job from the CI config as well

**Review by leseb — COMMENTED** [review]
A few things to consider:

* Is legacy training still supported?
* How about changing the current notebook to work with the newest version of the generated data
* Add a note to CHANGELOG, would have been nice to warn before hand, instead of brutality removing the script (assuming it has existing users, but that's hard to tell)

Thanks!

**Comment by nathan-weinberg** [comment]
This seems abandoned, and I'd honestly prefer having notebooks here in case someone wants to pick them up later. They're not hurting anyone in their current state.

Closing this for now.

**Pull request closed without merging**
