### PR TITLE
Add missing ilab model help screen descriptions

### PR DESCRIPTION
**Pull request by alinaryan**
Adds missing descriptions on the evaluate and download commands in the ilab model help screen. Also, capitalizes the List help text to be consistent with the others.

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by alinaryan** [comment]
New output:

```
(venv) alina@fedora:~/dev/instruct-lab/cli/instructlab$ ilab model --help
Usage: ilab model [OPTIONS] COMMAND [ARGS]...

  Command Group for Interacting with the Models in InstructLab.

  If this is your first time running ilab, it's best to start with `ilab
  config init` to create the environment.

Options:
  --help  Show this message and exit.

Commands:
  chat      Run a chat using the modified model
  convert   Converts model to GGUF
  download  Downloads model from a specified repository
  evaluate  Evaluates the trained model
  list      Lists models
  serve     Start a local server
  test      Runs basic test to ensure model correctness
  train     Takes synthetic data generated locally with `ilab data...
```

**Review by jaideepr97 — APPROVED** [review]
Thanks @alinaryan 
Could we make all the language consistent in terms of tense while we're at it?
```Run a chat...``` -> ```Runs a chat...```
```Start a local server``` -> ```Starts a local server```

**Comment by nathan-weinberg** [comment]
@alinaryan can you squash? can merge this in after :+1:

**Comment by alinaryan** [comment]
@nathan-weinberg Done

**Review by nathan-weinberg — APPROVED** [review]

**Pull request merged**
