### PR TITLE
chore: update minimum training library version

### PR DESCRIPTION
**Pull request by RobotSail**
To make use of the latest updates in the training library, this commit bumps the version
number from v0.3.2 to v0.4.0

Signed-off-by: Oleg S <97077423+RobotSail@users.noreply.github.com>

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by Maxusmusti — APPROVED** [review]
LGTM

**Review by nathan-weinberg — APPROVED** [review]

**Comment by nathan-weinberg** [comment]
This is failing mypy cause the lib just released and hasn't made it to PyPI yet

@RobotSail if you retrigger the check once the package is published it should pass

**Comment by RobotSail** [comment]
@nathan-weinberg Thank you for catching that, rerunning this check.

**Review by booxter — COMMENTED** [review]
Will need to fix `test_package_conflict`

**Review by booxter — APPROVED** [review]
Needed for https://github.com/instructlab/instructlab/pull/2004 that is a blocker.

**Review by JamesKunstle — APPROVED** [review]

**Pull request merged**
