### PR TITLE
Add Prompting FAQ for troubleshooting model responses

### PR DESCRIPTION
**Pull request by relyt0925**
This new FAQ document provides guidance on improving model responses when they fail to return desired results. It includes a detailed example that demonstrates how adding context can help the model produce accurate answers.

Resolves https://github.com/instructlab/instructlab/issues/2596 (part of the issue)

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Functional tests have been added, if necessary.
- [ ] E2E Workflow tests have been added, if necessary.

### CODE REVIEW

**Review by nathan-weinberg — CHANGES_REQUESTED** [review]
Thanks for this @relyt0925! Could you move the file into the `docs` directory?

**Comment by relyt0925** [comment]
For sure!

**Review by nathan-weinberg — APPROVED** [review]
LGTM - I'll let @kelbrown20 have final say before merge!

**Review by kelbrown20 — APPROVED** [review]
This looks awesome, Thank you for adding this! 
LGTM!

**Pull request merged**
