### PR TITLE
ci: add a ci validation for notebooks

### PR DESCRIPTION
**Pull request by leseb**
When a change occurs in notebooks/ on a .ipynb file, the CI will run and
validate it.

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by nathan-weinberg** [comment]
Thanks for this @leseb!

Would you mind hardening these actions as outlined in [this document](https://github.com/instructlab/dev-docs/blob/main/docs/github-actions-use-policy.md)? Happy to answer any questions around this!

**Review by russellb — COMMENTED** [review]
This lgtm pending the updates requested by @nathan-weinberg

**Review by russellb — APPROVED** [review]
Nothing in this repo has been upated for the guidelines referenced by @nathan-weinberg , including the dependabot addition for updating actions. I don't think we need to block this PR on it.

I think a separate PR to convert the repo to the proposed style is the best way to get started with those guidelines.

**Comment by leseb** [comment]
@nathan-weinberg @russellb https://github.com/instructlab/instructlab/issues/1218

**Pull request merged**
