### PR TITLE
Update gpu-acceleration.md with llama-cpp-python 0.2.75

### PR DESCRIPTION
**Pull request by rinaldodev**
# Changes
Update gpu-acceleration.md file to be in line with the recent update of llama-cpp-python 0.2.75 in https://github.com/instructlab/instructlab/commit/f24d0d7b5988f0999d821647a14c4500f7afa109

**Which issue is resolved by this Pull Request:**
N/A

**Description of your changes:**
- Change `CUBLAS` to `CUDA` in env vars.
- Change version from 0.2.55 to 0.2.75 where applicable.
- Change links to point to the fixed 0.2.75 branch/tag of the llama-cpp-python repo.

### CODE REVIEW

**Comment by rinaldodev** [comment]
DCO bot doesn't seem to like the `.` in `Jr.`

**Comment by rinaldodev** [comment]
Fixed.
```
commit ad7e9f76a8f6dedc67bfdf2668c762461698eb1c (HEAD -> patch-1, origin/patch-1)
Author: Rinaldo Pitzer Jr. <16694899+rinaldodev@users.noreply.github.com>
Date:   Thu Jun 6 13:34:56 2024 -0300

    Update gpu-acceleration.md with llama-cpp-python 0.2.75
    
    Signed-off-by: Rinaldo Pitzer Jr. <16694899+rinaldodev@users.noreply.github.com>
```

**Comment by nathan-weinberg** [comment]
Can you change the commit email to be your actual email @rinaldodev? Might fix the issue. Right now I'm seeing `<16694899+rinaldodev@users.noreply.github.com>`

**Comment by tiran** [comment]
`README.md` also uses `LLAMA_CUBLAS`. Please fix it there, too.

**Comment by rinaldodev** [comment]
> Can you change the commit email to be your actual email @rinaldodev? Might fix the issue. Right now I'm seeing `<16694899+rinaldodev@users.noreply.github.com>`
The bot was already satisfied when I checked it today, but anyway I updated the email to a real one.
Sorry for the delay, I was waiting the creation of a new email alias.


> `README.md` also uses `LLAMA_CUBLAS`. Please fix it there, too.
Done. The CI also seems to use "CUBLAS", but I haven't taken the time to check if it points to the main branch or a stable one that still uses the previous 0.2.55 llama-cpp-python.

**Comment by rinaldodev** [comment]
> Please add the PR description into your commit message. All the following:
> 
> Change CUBLAS to CUDA in env vars. Change version from 0.2.55 to 0.2.75 where applicable. Change links to point to the fixed 0.2.75 branch/tag of the llama-cpp-python repo.
> 
> Thanks!

Done.

**Review by leseb — APPROVED** [review]

**Review by nathan-weinberg — APPROVED** [review]

**Pull request merged**
