### PR TITLE
refactor ensure_server, run_detached: return api_base

### PR DESCRIPTION
**Pull request by makelinux**
Avoid duplicated code and shorten long functions.

### CODE REVIEW

**Review by leseb — APPROVED** [review]

**Comment by tiran** [comment]
@Mergifyio rebase

**Review by leseb — DISMISSED** [review]

**Comment by tiran** [comment]
@Mergifyio rebase

**Comment by makelinux** [comment]
@leseb , would you like please to check false report and review the PR?

**Comment by tiran** [comment]
@makelinux Please rebase

**Review by leseb — APPROVED** [review]

**Review by alimaredia — CHANGES_REQUESTED** [review]
@makelinux I like this refactor! You missed one very new instance of `run_detached` though: https://github.com/instructlab/instructlab/blob/main/src/instructlab/model/evaluate.py#L241

**Review by alimaredia — APPROVED** [review]

**Comment by makelinux** [comment]
@leseb , @tiran , Would you like to add the final approval please?

**Review by tiran — APPROVED** [review]

**Pull request merged**
