### PR TITLE
ci: use FSDP distributed backend for training in L40sx4 job

### PR DESCRIPTION
**Pull request by alimaredia**
**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Functional tests have been added, if necessary.
- [x] E2E Workflow tests have been added, if necessary.

### CODE REVIEW

**Comment by alimaredia** [comment]
Feel free to review, but I'm adding the hold label until I can run training successfully by hand

**Comment by nathan-weinberg** [comment]
cc @Maxusmusti

**Comment by nathan-weinberg** [comment]
> e2e workflow failed on this PR: [View run](https://github.com/instructlab/instructlab/actions/runs/11258106253), please investigate.

This failed on Eval but Training did succeed!

**Review by RobotSail — APPROVED** [review]
LGTM

**Pull request merged**
