### PR TITLE
Attempt minimal approach to restructuring ilab commands

### PR DESCRIPTION
**Pull request by russellb**
This started while I was reviewing #990. I was trying to understand the specific
changes necessary to implement the new `ilab` command structure. This PR is what
I ended up with.

These changes do not attempt to implement the full scope of what is envisioned
with restructuring the code base in a structure that is similar to the commands.
Instead, it tries to only make the new commands work with the smallest amount of
change.

What it does:

- New commands are functional
- Old commands are still supported, but emit a deprecation warning
- Config file remains the same

What is not included:

- Reorganizing the code to more logically follow the command structure
- test changes to exercise the new commands
- doc changes to reflect new commands

51ddd7a Create `ilab config init` command
4f33406 Add `ilab data generate`
fd04c30 Map configuration file to the new commands
8ab8a5e Add `ilab taxonomy diff`
495773a Add `ilab system info`
36e4c49 Add `ilab model` command group
bcc9057 Add `ilab model chat`
daa522b Add `ilab model convert`
96b43f5 Add `ilab model download`
b27eb3b Add `ilab model serve`
6ebf165 Add `ilab model evaluate`
d34a628 Add `ilab model train`
e6c7f6f Adjust `ilab diff` tests to use new `ilab taxonomy diff`

commit 51ddd7a49dbe29e539afa7fb15b2a8e1f2e57743
Author: Russell Bryant <rbryant@redhat.com>
Date:   Tue Jun 4 20:36:04 2024 -0400

    Create `ilab config init` command
    
    This change adds a new command, `ilab config init`, which shares the
    same implementation with `ilab init`. If a user runs `ilab init`
    instead, they will get a red warning message saying that this command
    is deprecated.
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

commit 4f334064e99c9914e2dee032ed0d99c8002d4faa
Author: Russell Bryant <rbryant@redhat.com>
Date:   Wed Jun 5 15:31:22 2024 -0400

    Add `ilab data generate`
    
    This change adds a new command `ilab data generate`. `ilab generate`
    works as an alias and will emit a deprecation warning when used.
    
    Part of https://github.com/instructlab/dev-docs/blob/main/docs/ilab-model-engine.md
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

commit fd04c304b32a0274d6b8efa6a86c077e8cd00968
Author: Russell Bryant <rbryant@redhat.com>
Date:   Wed Jun 5 20:12:17 2024 -0400

    Map configuration file to the new commands
    
    This commit makes all configuration work for the new commands. It does
    not change the configuration format to a new structure. That should be
    considered in some follow-up work.
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

commit 8ab8a5e08479877c7e966d383b98e6f1cc83cb36
Author: Russell Bryant <rbryant@redhat.com>
Date:   Wed Jun 5 15:43:50 2024 -0400

    Add `ilab taxonomy diff`
    
    This change adds a new command `ilab taxonomy diff`. `ilab diff`
    works as an alias and will emit a deprecation warning when used.
    
    Part of https://github.com/instructlab/dev-docs/blob/main/docs/ilab-model-engine.md
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

commit 495773a68882fa40d148305e35536966ee9dabd6
Author: Russell Bryant <rbryant@redhat.com>
Date:   Wed Jun 5 15:47:33 2024 -0400

    Add `ilab system info`
    
    This change adds a new command `ilab system info`. `ilab sysinfo`
    works as an alias and will emit a deprecation warning when used.
    
    Part of https://github.com/instructlab/dev-docs/blob/main/docs/ilab-model-engine.md
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

commit 36e4c49e22ce656ba55ccf688f0d95ba59057706
Author: Russell Bryant <rbryant@redhat.com>
Date:   Wed Jun 5 15:49:30 2024 -0400

    Add `ilab model` command group
    
    This introduces the command group `model`. Several commands will be
    moved into this group in commits following this one.
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

commit bcc905753b3122b2515ad34ff704df99687c626b
Author: Russell Bryant <rbryant@redhat.com>
Date:   Wed Jun 5 15:52:12 2024 -0400

    Add `ilab model chat`
    
    Add `ilab model chat`. Use of `ilab chat` will emit a deprecation
    warning.
    
    https://github.com/instructlab/dev-docs/blob/main/docs/ilab-model-engine.md
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

commit daa522bc5f428c9eb9d8057143905301fab6963f
Author: Russell Bryant <rbryant@redhat.com>
Date:   Wed Jun 5 15:54:31 2024 -0400

    Add `ilab model convert`
    
    Add `ilab model convert` command. `ilab convert` will emit a
    deprecation warning if used.
    
    Part of https://github.com/instructlab/dev-docs/blob/main/docs/ilab-model-engine.md
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

commit 96b43f510b163766007915778ed98bf59308ceb4
Author: Russell Bryant <rbryant@redhat.com>
Date:   Wed Jun 5 15:56:12 2024 -0400

    Add `ilab model download`
    
    Add command `ilab model download`. The old command `ilab download`
    still works and will emit a deprecation warning if used.
    
    https://github.com/instructlab/dev-docs/blob/main/docs/ilab-model-engine.md
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

commit b27eb3b035a1360f1710a4e882f14a07033431da
Author: Russell Bryant <rbryant@redhat.com>
Date:   Wed Jun 5 20:46:10 2024 -0400

    Add `ilab model serve`
    
    Both the new command and `ilab serve` both work. The old command will
    emit a deprecation warning if used.
    
    https://github.com/instructlab/dev-docs/blob/main/docs/ilab-model-engine.md
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

commit 6ebf16528e6ee1e0c6c47a79a67e858432ed2397
Author: Russell Bryant <rbryant@redhat.com>
Date:   Wed Jun 5 20:51:45 2024 -0400

    Add `ilab model evaluate`
    
    This new command and `ilab test` both work. The old command will emit
    a deprecation warning if used.
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

commit d34a62870d169395e42b5a6907280771a1f56c72
Author: Russell Bryant <rbryant@redhat.com>
Date:   Wed Jun 5 20:53:34 2024 -0400

    Add `ilab model train`
    
    This command and `ilab train` both work, but the old command will emit
    a deprecation warning if used.
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

commit e6c7f6f93a9b2f75a09ee6a26484f54c253db9b4
Author: Russell Bryant <rbryant@redhat.com>
Date:   Wed Jun 5 21:43:22 2024 -0400

    Adjust `ilab diff` tests to use new `ilab taxonomy diff`
    
    Some of the tests in this file were checking the output of the
    command, which now included a message about using a deprecated
    command. To make all the tests work as before, use the new command
    name.
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

### CODE REVIEW

**Comment by russellb** [comment]
@cdoern am I missing anything in this simple example? I was trying to understand the core of the changes necessary for the changes proposed in #990.

**Comment by cdoern** [comment]
@russellb a few things here that come to mind: because of shared dependency of commands, my code moves the helper functions shared btwn functions to a common file and package.

The main reason for this consolidation is the idea of not keeping all functions in lab.py. Separated click groups implies different functionality and feature sets which in pythonic terms means separate packages (at least in my head). My PR splits each command group into its own package where each file is a command or a parent group command. Separate files and pkgs means I needed to move things out of lab.py and elsewhere to avoid circular dependencies.

I think springing for this design makes sense for our timeline but the design in my PR needs to happen eventually. I think ~10 days is enough time to get my design in as long as the purpose of it is understood.

a big part of the redesign was clearing up user confusion and opening up the door for easier community contributions, this structure IMO adds more confusion than before if the cmds in different groups are found in the same file. When proposing my design especially keeping in mind more future command implementations and API expansions, the split design was always my choice of implementation. If others in the @instructlab/cli-maintainers group feel strongly I'd be happy to discuss this. However, the diagram and explanation in my design doc: 

```
ilab
|
|_______model
|       |
|       |____convert
|       |____download
|       |____train
|       |____serve
|       |____chat
|       |____evaluate
|       |
|_______data
|       |
|       |____generate
|       |
|_______config
|       |
|       |____init
|       |
|_______taxonomy
|       |
|       |____diff
|       |____check
|       |____download
```
were meant to serve both for command structure and code structure. My design doc also points this in text:

```
this workflow not only adds *purposeful organization to this project*, but will encourage contributors to add commands as they use ilab, and file bugs in *specific parts of the codebase* that need work as opposed to the current flow which is hard to keep track of from a user's point of view.
```

**Comment by cdoern** [comment]
This also doesn't cover aliases which I am working on now. My general idea is to either

1. add the commands multiple times to the ilab group once with something like `model list` and then again as just `list`
2. implement a custom cmd class as is suggested on click's documentation

**Comment by russellb** [comment]
> This also doesn't cover aliases which I am working on now. 

It does handle it. Both `ilab init` and `ilab config init` work and you get a deprecation warning on `ilab init`.

**Comment by cdoern** [comment]
I am still going to die on this hill that a single file approach cannot be the way we introduce this as it was a core part of the design doc

**Comment by russellb** [comment]
> I am still going to die on this hill that a single file approach cannot be the way we introduce this as it was a core part of the design doc

Understood!  We talked about this more offline. I'm going to keep this open as a reference for how click works in the context of adding the new command types, but I'm keeping it as a Draft to make it clear it's not a proposal to merge this.

**Comment by leseb** [comment]
@russellb should we close this now?

**Pull request closed without merging**
