### PR TITLE
notebook: more clean results code and output

### PR DESCRIPTION
**Pull request by makelinux**
Improvements of notebook results:
1. Shorter, cleaner and more maintainable code and output.
2. Markdown format of output is suitable for copy-paste to PR.
3. Pre-trained text is truncated because usually it is hallucinated and not valuable. It is only used as baseline to see improvement of fine-tuned results.
4. Pre-trained text written in italic font to distinguish it visually from provided in qna.yaml and fine-tuned.

### CODE REVIEW

**Comment by leseb** [comment]
Please hold until the CI can validate the notebook with https://github.com/instructlab/instructlab/pull/1202. Thanks

**Comment by makelinux** [comment]
> Looking at the Notebook here https://github.com/instructlab/instructlab/blob/7149dc6b03ae495e34f7270a75c0ecf67c7b1f9e/notebooks/Training_a_LoRA_With_Instruct_Lab.ipynb, GitHub says it's invalid.

Actually it is here: https://github.com/RedHat-Israel/instructlab/blob/7149dc6b03ae495e34f7270a75c0ecf67c7b1f9e/notebooks/Training_a_LoRA_With_Instruct_Lab.ipynb?short_path=904508c

**Comment by leseb** [comment]
@Mergifyio rebase

**Comment by leseb** [comment]
@makelinux please rebase

**Review by russellb — APPROVED** [review]

**Review by leseb — APPROVED** [review]

**Pull request merged**
