### PR TITLE
chore!: Update Python 3.12 and PyTorch 2.4.1

### LINKED ISSUE #1463: Support Python 12
**Is your feature request related to a problem? Please describe.**

Support for Python 12 is being withdrawn in https://github.com/instructlab/instructlab/pull/1461 for reasons.

**Describe the solution you'd like**

This will need to be resolved so py12 support can be brought back.  It's the only real active Python version right now and will be popular for the next few years.

**Additional context**

### PR DESCRIPTION
**Pull request by fabiendupont**
BREAKING CHANGE: Update Python to 3.12 and PyTorch to 2.4.1

Now that PyTorch 2.4 supports Python 3.12, This change attempts updating the default Python version to 3.12. It also brings the update to PyTorch 2.4.1 and all its dependencies. One of these dependencies is AMD ROCm 6.1. So, it ends up being a massive change.

Intel Gaudi (HPU) remains on Intel fork of PyTorch 2.3.1.

It also requires the other repositories to update their dependencies accordingly, so it requires some coordination.

Resolves #1463

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Functional tests have been added, if necessary.
- [ ] E2E Workflow tests have been added, if necessary.

### CODE REVIEW

**Comment by bjhargrave** [comment]
Has the dolomite dependency been updated to support Python 3.12?

https://github.com/instructlab/training/blob/f33994de30a89023b8a38a2d38d197aadadd7218/requirements.txt#L20

See https://github.com/instructlab/instructlab/pull/1461#issuecomment-2189635889

**Comment by nathan-weinberg** [comment]
This definitely requires a CHANGELOG update

**Comment by tiran** [comment]
I could not find a ticket, so I have filed #2437 for PyTorch 2.4.0.

Can we please do Torch 2.4 and Python 3.12 in two separate PRs? They are big, potentially disruptive, and unrelated changes. Torch 2.4 is also more pressing than Python 3.12. We need Torch 2.4. for Gaudi 3 support, ROCm performance improvements, and newer vLLM with fixes.

Is there any technical reason that we **must** update Python to 3.12? As far as I'm aware, it is currently just a nice to have that might give us a little performance improvement.

**Comment by tiran** [comment]
PS: Intel Gaudi software 1.18.0 is on Python 3.11. We have to keep Python 3.11 as our primary, fully tested version for now.

**Comment by fabiendupont** [comment]
@tiran, it's not a must, but somehow the sooner we move, the less under pressure later, even though the adoption of 3.12 is not really fast.

**Comment by nathan-weinberg** [comment]
Should we close this in favor of https://github.com/instructlab/instructlab/pull/2445?

**Pull request closed without merging**
