### PR TITLE
removes os.system in lab.py

### LINKED ISSUE #530: Replace os.system("python ...") with subprocess.check_call([sys.executable, ...])
The `cli.lab` uses `os.system()` to run sub processes. The use of `os.system` is problematic for two major reasons:

* The call does not raise an exception if a sub process fails. The main program just continues to run.
* The function requires a properly shell-escaped argument. If the argument is not correctly escaped for the user's current shell, then the command can fail in all sorts of funny ways, e.g. with space or non-ASCII directory name.

I highly recommend to replace any use of `os.system()` with `subprocess.check_call()`

Instead of
```python
cmd = f"{script} --gguf {gguf_model_path} --repo {tokenizer_dir} --mlx-path {dest_model_dir}"
os.system("python {}".format(cmd))
```
do
```python
subprocess.check_call([sys.executable, script, "--gguf", gguf_model_path, "--repo", tokenizer_dir, "--mlx-path", dest_model_dir])
```

`check_call()` checks the exit status of a command and fails with an exception if the program fails.

### PR DESCRIPTION
**Pull request by wgahnagl**
# Changes

**Which issue is resolved by this Pull Request:**
Resolves #530

**Description of your changes:**
removes the os.system in lab.py! These changes are untested since we don't have a working mac set up for this! If someone with a mac could test before merging it would be much appreciated!

re-open of closed PR #862

### CODE REVIEW

**Comment by nathan-weinberg** [comment]
@wgahnagl Not necessarily opposed to the current implementation but can I ask why you chose `check_call` instead of `run`? https://docs.python.org/3/library/subprocess.html#using-the-subprocess-module

**Comment by nathan-weinberg** [comment]
After reading a little closer I realize now this was called for explicitly by the original issue - @tiran could you answer the above q?

**Comment by tiran** [comment]
This PR conflicts with the proposed fix for #438 . I plan to move the quantize binary into a separate package that provides a `run_quantize` function:

```
from instructlab_quantize import run_quantize
run_quantize("llama.cpp/models/ggml-vocab-llama.gguf", "Q4_K_M")
```

**Comment by nathan-weinberg** [comment]
Given @tiran's comment above, I'm going to close this in favor the fix for #438

**Pull request closed without merging**
