### PR TITLE
fix: cap trl version at v0.12.x

### LINKED ISSUE #2803: trl v0.13 breaks our usage of SFTTrainer in legacy training
**Describe the bug**

In `trl` v0.13, the `SFTTrainer` was updated so that all training parameters must now be passed to `SFTConfig` instead of being given directly to `SFTTrainer`. 

This is resulting in E2E errors: https://github.com/instructlab/instructlab/actions/runs/12356758127/job/34483795562?pr=2797#step:7:2825

**To fix**:

We just need to update the code to pass parameters to `SFTConfig` instead of `SFTTrainer`, or cap the version at `v0.12`

### PR DESCRIPTION
**Pull request by RobotSail**
There is currently a bug which affects how SFTTrainer consumes training-time
parameters. This PR updates the version of trl such that our existing code
does not break PRs

Signed-off-by: Oleg S <97077423+RobotSail@users.noreply.github.com>

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Functional tests have been added, if necessary.
- [ ] E2E Workflow tests have been added, if necessary.

### CODE REVIEW

**Review by nathan-weinberg — APPROVED** [review]
Related to https://github.com/instructlab/instructlab/issues/2803

This will unblock CI will we investigate making a code change - thanks for the quick patch @RobotSail!

**Comment by nathan-weinberg** [comment]
Should we opt for https://github.com/instructlab/instructlab/pull/2805 instead of this?

**Comment by RobotSail** [comment]
@nathan-weinberg Not sure, I provided both since one is short-term and one is long-term. Depends on which one will make backporting less painful.

**Comment by nathan-weinberg** [comment]
Honestly I say we opt for the long-term PR - backporting shouldn't be too bad, I'm happy to shepherd that along - @cdoern wdyt?

**Comment by cdoern** [comment]
I agree and approved the other one

**Comment by RobotSail** [comment]
Sounds good, will close this one then.

**Pull request closed without merging**
