### PR TITLE
list contexts

### PR DESCRIPTION
**Pull request by reidliu41**
During the chat(or specify in cli), it can change the `context`,  actually, no any tips show what are the available contexts are? And what is the content? Besides  wrong input, it will tell.
~~~
>>> /c xx                                                                              [S][default]
╭──────────────────────────────────────────── system ─────────────────────────────────────────────╮
│ WARNING: Context xx not found. Available contexts: default, cli_helper                          │  
╰─────────────────────────────────────────────────────────────────────────────────────────────────╯
>>> /h                                                                                       [S][default]
╭─────────────────────────────────────────────── system ────────────────────────────────────────────────╮
│ Help / TL;DR                                                                                          │
│                                                                                                       │
│  • /q: quit                                                                                           │
│  • /h: show help                                                                                      │
│  • /a assistant: amend assistant (i.e., model)                                                        │
│  • /c context: change context
~~~

So tried to add the tips and list the content.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Functional tests have been added, if necessary.
- [ ] E2E Workflow tests have been added, if necessary.

### CODE REVIEW

**Comment by reidliu41** [comment]
```
# show the available contexts:

$ ilab model chat --help
Usage: ilab model chat [OPTIONS] [QUESTION]...

  Runs a chat using the modified model

Options:
  -m, --model TEXT          Model to be used for chatting with. [required;
                            default: /Users/reidl/.cache/instructlab/models/me
                            rlinite-7b-lab-Q4_K_M.gguf; config: 'chat.model']
  -c, --context TEXT        Predefined setting or environment that influences
                            the behavior and responses of the chat assistant.
                            Each context is associated with a specific prompt
                            that guides the assistant on how to respond to
                            user inputs. Available contexts: default,
                            cli_helper. [required; default: default; config:
                            'chat.context']


>>> /h                                                                         [S][default]
╭──────────────────────────────────────── system ─────────────────────────────────────────╮
│ Help / TL;DR                                                                            │
│                                                                                         │
│  • /q: quit                                                                             │
│  • /h: show help                                                                        │
│  • /a assistant: amend assistant (i.e., model)                                          │
│  • /c context: change context (available contexts: default, cli_helper)                 │
│  • /lc: list contexts


>>> /lc                                                                        [S][default]
╭──────────────────────────────────────── system ─────────────────────────────────────────╮
│ Available contexts:                                                                     │
│                                                                                         │
│ default: I am, Red Hat® Instruct Model based on Granite 7B, an AI language model        │
│ developed by Red Hat and IBM Research, based on the Granite-7b-base language model. My  │
│ primary function is to be a chat assistant.                                             │
│                                                                                         │
│ cli_helper: You are an expert for command line interface and know all common commands.  │
│ Answer the command to execute as it without any explanation.                            │
╰─────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by nathan-weinberg** [comment]
Please include a description of the change per the PR template, thanks.

**Comment by reidliu41** [comment]
> Please include a description of the change per the PR template, thanks.

sorry, feel free to take a look

**Comment by reidliu41** [comment]
hi, please someone help to take a look

**Comment by reidliu41** [comment]
> Thanks @reidliu41 would you be able to add a small unit test to verify the output reflects the changes?

thanks for your reply. seems no test for previous chat code in `test_chat.py`, but for `functional-tests.sh`, 
or any places I missed? feel free to share.

**Comment by reidliu41** [comment]
> Thanks @reidliu41 would you be able to add a small unit test to verify the output reflects the changes?

updated

**Review by jaideepr97 — APPROVED** [review]
LGTM, thanks @reidliu41 !

**Review by nathan-weinberg — APPROVED** [review]

**Pull request merged**
