### PR TITLE
e2e: Run on PRs and pushes

### PR DESCRIPTION
**Pull request by russellb**
The e2e workflow seems stable and I've cleared the budget side of
running this a lot more often. Turn on running it on all code changes.

Signed-off-by: Russell Bryant <rbryant@redhat.com>

### CODE REVIEW

**Review by leseb — COMMENTED** [review]
Should we remove the code that triggers on labels too? It does not seem needed anymore.

**Comment by russellb** [comment]
> Should we remove the code that triggers on labels too? It does not seem needed anymore.

good point ...

**Comment by russellb** [comment]
> > Should we remove the code that triggers on labels too? It does not seem needed anymore.
> 
> good point ...

done!

**Review by nathan-weinberg — APPROVED** [review]

**Review by leseb — CHANGES_REQUESTED** [review]
A few more things need to go away from `.github/workflows/e2e.yml`:

* logic about detecting whether this is a PR or not: it's always a PR
* All the logic about commenting on the PRs on success/failure
* `workflow_dispatch`
* Checkout branch step

Thanks!

**Comment by nathan-weinberg** [comment]
> A few more things need to go away from `.github/workflows/e2e.yml`:
> 
>     * logic about detecting whether this is a PR or not: it's always a PR
> 
>     * All the logic about commenting on the PRs on success/failure
> 
>     * `workflow_dispatch`
> 
>     * Checkout branch step
> 
> 
> Thanks!
> 
> EDIT: I think keeping `gh` CLI does not hurt even if not used anymore.

If we get rid of `workflow_dispatch` we should also update the release documentation as that calls for a manual E2E run to be done on the release branch before drafting the release.

@russellb it may also be good to update the `ci.md` doc with some of the changes, but I won't block based on that

**Comment by russellb** [comment]
> A few more things need to go away from `.github/workflows/e2e.yml`:
> 
> * logic about detecting whether this is a PR or not: it's always a PR

This only applies when manually triggered. I think it doesn't hurt to keep.

> * All the logic about commenting on the PRs on success/failure

I think this will only run if someone manually triggers the job against a PR.

> * `workflow_dispatch`

This is necessary for triggering it against a specified branch at a minimum. I suppose triggering on a PR isn't that interesting since that will already happen automatically.

I think I'd rather keep it though.  We may want to allow manually triggering on a PR with some additional options. Maybe we can let manually triggering it run it with a different model type, options to run more extensive training, ... probably a lot of potenntial.

> * Checkout branch step

I'd like to keep it to allow manually triggering the workflow against a branch. It's part of the release process at the moment.

I suppose it's going to run automatically every time a release branch changes, anyway, so maybe it's not needed in practice ... but similar to the discussion above about PRs, I think we might have use for this to allow triggering the workflow with parameters to do different variations.

Can we keep it for now to allow exploring more inputs for custom job runs?

**Comment by leseb** [comment]
> > A few more things need to go away from `.github/workflows/e2e.yml`:
> > 
> > * logic about detecting whether this is a PR or not: it's always a PR
> 
> This only applies when manually triggered. I think it doesn't hurt to keep.
> 
> > * All the logic about commenting on the PRs on success/failure
> 
> I think this will only run if someone manually triggers the job against a PR.
> 
> > * `workflow_dispatch`
> 
> This is necessary for triggering it against a specified branch at a minimum. I suppose triggering on a PR isn't that interesting since that will already happen automatically.
> 
> I think I'd rather keep it though. We may want to allow manually triggering on a PR with some additional options. Maybe we can let manually triggering it run it with a different model type, options to run more extensive training, ... probably a lot of potenntial.
> 
> > * Checkout branch step
> 
> I'd like to keep it to allow manually triggering the workflow against a branch. It's part of the release process at the moment.
> 
> I suppose it's going to run automatically every time a release branch changes, anyway, so maybe it's not needed in practice ... but similar to the discussion above about PRs, I think we might have use for this to allow triggering the workflow with parameters to do different variations.
> 
> Can we keep it for now to allow exploring more inputs for custom job runs?

Alright alright :). I don't want to block that PR for that, we can revisit the config later. Thanks!

**Review by leseb — APPROVED** [review]

**Pull request merged**
