### PR TITLE
fix: ilab config init improperly sets generate model

### PR DESCRIPTION
**Pull request by cdoern**
even though the defaults in the config file are mistral, ilab config init overrides these with merlinite due to some old logic that assumes merlinite is the model you want to use for everything

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Functional tests have been added, if necessary.
- [ ] E2E Workflow tests have been added, if necessary.

### CODE REVIEW

**Review by alinaryan — APPROVED** [review]

**Review by RobotSail — APPROVED** [review]

**Comment by cdoern** [comment]
ci is being weird/failing due to rate limits

**Comment by jaideepr97** [comment]
@cdoern can we use this opportunity to remove that entire block?

**Comment by cdoern** [comment]
actually, I think for now we need to keep it, right? Otherwise this PR would need to change `ilab config init` to not prompt for both

a. taxonomy path
b. model path

if we remove this block, then taxonomy path is never set in the cfg, nor is the chat/serve model (merlinite)

**Comment by nathan-weinberg** [comment]
@cdoern rebasing will fix CI

**Comment by cdoern** [comment]
rebased ontop of testing fixes

**Comment by nathan-weinberg** [comment]
@Mergifyio backport release-v0.19

**Comment by jaideepr97** [comment]
> if we remove this block, then taxonomy path is never set in the cfg, nor is the chat/serve model (merlinite)
@cdoern 
everything is set into the config object out of the box, what the user responds with to the prompt only overwrites that 
https://github.com/instructlab/instructlab/blob/main/src/instructlab/configuration.py#L251
https://github.com/instructlab/instructlab/blob/main/src/instructlab/configuration.py#L120

**Comment by cdoern** [comment]
@jaideepr97 if they pass a custom taxonomy path and we remove this block it doesn't get propogated into the cfg. I did this locally , ran the tests and that failed 😢 

I think if that is the case its out of scope for this PR (thats more of a feature change)

**Comment by cdoern** [comment]
i do think scoping a fundamental change to ilab config init is necessary tbh

**Pull request merged**
