### PR TITLE
CPU training optimization

### PR DESCRIPTION
**Pull request by russellb**
This is a rebased copy of the PR originally in #1109 and is related to issue
#1006.

I wanted to test it out and see if we should revisit the changes, but needed to
rebase first. Since I did the rebase, I figured I'd go ahead and post it as a
draft while playing with it.

I'll update the title, description, and series of commits prior to a request for
review if we get that far.

### CODE REVIEW

**Comment by tiran** [comment]
My PR #993 contains most bits of #1006, too.

**Comment by russellb** [comment]
> My PR #993 contains most bits of #1006, too.

Oh, thanks! I'll focus on that one, then.

**Comment by russellb** [comment]
Actually, I'll keep this draft open for the moment since I'm in the middle of testing these CPU focused changes on their own ... but obviously if we can get #993 in this is not necessary

**Comment by russellb** [comment]
Similar to the comment on #1225, ilab gets OOM killed using this PR on my laptop with 32 GB RAM.

**Comment by russellb** [comment]
I'm working through some follow-up changes necessary on #993 now

**Pull request closed without merging**
