### PR TITLE
Knowledge v3 support

### PR DESCRIPTION
**Pull request by russellb**
See epic instructlab/sdg#160 for more information.

cc71e8b requirements: Make use of knowledge v3 versions of dependencies
fd50d86 e2e: Update knowledge sample to a v3 example

commit cc71e8bef521d04d112da116590f0bf427580475
Author: Russell Bryant <rbryant@redhat.com>
Date:   Thu Jul 18 16:19:51 2024 -0400

    requirements: Make use of knowledge v3 versions of dependencies
       
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

commit fd50d866bea75991de902f5749ceee63c3dc5d25
Author: Russell Bryant <rbryant@redhat.com>
Date:   Thu Jul 18 16:20:45 2024 -0400

    e2e: Update knowledge sample to a v3 example
    
    The knowledge schema changed to v3. Older versions are no longer
    supported. Update our testing accordingly.
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

### CODE REVIEW

**Comment by russellb** [comment]
This passes CI now, but it requires:
- instructlab-schema release
- instructlab-sdg release

**Comment by russellb** [comment]
Note that https://github.com/instructlab/instructlab/pull/1767 should go in first as it removes code that would be broken against v3 knowledge files

**Comment by markmc** [comment]
> Note that #1767 should go in first as it removes code that would be broken against v3 knowledge files

Merged now.

**Review by derekhiggins — APPROVED** [review]
lgtm

**Pull request merged**
