### PR TITLE
Fix workflow-complete jobs for use by status check jobs

### PR DESCRIPTION
**Pull request by bjhargrave**
The workflow-complete jobs used job.needs which meant their job ids did not show up in the check-runs until they started. This can be some time since lint jobs take ~20min (and test jobs ~40min). Since the workflow-complete job ids do not appear for quite some time, the status checks in other jobs do not see them and properly wait for them to complete. For example, this allowed the test jobs to start while the lint jobs were still executing.

We change from using job.needs to using a status checks workflow to wait for the member jobs to complete. This quickly creates the entry in check-runs for the workflow-complete jobs which then allows other status check jobs to see these job ids and wait upon their completion.

Since the workflow-complete job's names are nested, we update the mergify config to use a regex match rather than an exact match.

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Functional tests have been added, if necessary.
- [ ] E2E Workflow tests have been added, if necessary.

### CODE REVIEW

**Comment by bjhargrave** [comment]
The pylint failure is not related to this PR. It must be something in main.

But this failure did demonstrate the workflow changes working. The test jobs did not start because they waited for the lint jobs to complete successfully but that did not happen.

**Comment by cdoern** [comment]
the pylint error is from bumping the training library. I can make a Pr to fix

**Comment by danmcp** [comment]
@mergifyio rebase

**Review by nathan-weinberg — APPROVED** [review]

**Review by cdoern — APPROVED** [review]

**Comment by bjhargrave** [comment]
Manually merging since the mergify config in the main branch does not recognize the new nested job names of the workflow-complete job names. The PR includes the changes to recognize the nested workflow-complete job names

**Pull request merged**
