### PR TITLE
add e2e testing for quantized backend training

### PR DESCRIPTION
**Pull request by cdoern**
adds another training test which runs after the `--legacy=true` test

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by russellb** [comment]
It looks like e2e actually failed, but it says it passed, not sure why 

https://github.com/instructlab/instructlab/actions/runs/9702039128/job/26776964340?pr=1494

**Comment by cdoern** [comment]
huh yeah I noticed that @russellb I will see if I can get it passing today

**Comment by cdoern** [comment]
switched to merlinite, lets see if that gets around ampere limitation. If not @Maxusmusti has a fix in training library to disable flash attn

**Comment by cdoern** [comment]
wondering if we should close this in favor of just using the A10s in #1557 @russellb @Maxusmusti  WDYT? Is there any chance with lora I could get this running on the smaller instances?

**Comment by Maxusmusti** [comment]
@cdoern what GPU is being used in these instances?

**Comment by russellb** [comment]
@cdoern yeah, focusing new training on the larger instances makes sense to me.

I'm going to propose a workflow that uses 4x A10Gs. I think that would be a great place to introduce this coverage.

**Comment by cdoern** [comment]
closing in favor of #1557 which merged. If we need this version we can reopen another PR

**Pull request closed without merging**
