### PR TITLE
wip: re-use spawn for temp server

### PR DESCRIPTION
**Pull request by leseb**

### CODE REVIEW

**Comment by leseb** [comment]
please someone add the "hold" label to this PR :)

**Comment by alimaredia** [comment]
@leseb I see you removed the "wip" from the title. Should we remove the "hold" label as well?

**Comment by leseb** [comment]
> @leseb I see you removed the "wip" from the title. Should we remove the "hold" label as well?

Not yet.

**Comment by leseb** [comment]
Looks like https://github.com/instructlab/instructlab/pull/1050 might solve this. I might revisit later if needed.

**Pull request closed without merging**
