### PR TITLE
 Add optional requirements for all hardware targets

### PR DESCRIPTION
**Pull request by tiran**
This adds `instructlab[cpu]`, `instructlab[rocm]`, and `instructlab[mps]` in additional to `instructlab[cuda]` and `instructlab[hpu]`. All test scripts, documentation, and tox have been updated to use the optional requirements.
g resolved

**Issue resolved by this Pull Request:**
Follup up PR on top of #1750 

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [x] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [x] Unit tests have been added, if necessary.
- [x] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by booxter** [comment]
The change is fine.

---

I have a question that is maybe relevant. Perhaps you can enlighten me.

Since recently, pytorch was bumped to require versions that are not available on at least some platforms (bug report [here](https://github.com/instructlab/instructlab/issues/1469)). This broke bare `tox` invocation on macosx x86_64. (only linux builds are uploaded on pypi for the CPU.)

Would this `extras` mechanism apply here too? Namely, to have different version requirements depending on the platform. (The current requirements for the library are confusing to me: we seem to require 2.2.2* for python3.10 but 2.3.0* for python3.11 - I think the intent was to have different versions per *platform*, not per *python version*?)

The way requirements for pytorch are specified, it's impossible to even run unit tests on a non-arm64 Mac. (This forced me into a linux vagrant box to work on the code base - which is a bit annoying.)

Could this mechanism help?

**Comment by tiran** [comment]
Yes, the approach can and will be used to make our requirements easier to define. Optional dependencies are additive to base requirements. An optional requirement can neither remove a base dependency nor broaden the version range. Something like `torch>=2.3.0` in base and `torch>=2.2.2a0` does not work. The base `requirements.txt` has to define broad version range. Targets can then narrow down the version range.

The Python 3.10 madness comes from Intel Gaudi support. It will go away soon. I don't want to address that topic in this PR for multiple reasons. For one, I have to write a test check for conflicts. It's possible but non-trivial with resolvelib.

Is there a ticket for Intel Mac support?

**Review by leseb — COMMENTED** [review]
What's the behavior of `pip install instructlab` now?

**Comment by tiran** [comment]
> What's the behavior of `pip install instructlab` now?

Right now, it should work with CPU and may work with CUDA. In the future, it's going to become a problem. There is no easy way to force a user to select an optional dependency.

We could do something sneaky to remind users to install optional dependencies:
- add an empty package like `instructlab-accelerator` or `instructlab-hardware`
- add a dependency on the package to all accelerator requirements file, but not to the base `requirements.txt` 
- add a check to `instructlab.lab` to check for the presence of the empty package and raise a helpful error when it is missing.

`pip install instructlab` won't install the package, but `pip install instructlab[cuda]` or `pip install instructlab[cpu]` will install it.

**Review by nathan-weinberg — APPROVED** [review]
Related doc issue opened by @cdoern: https://github.com/instructlab/instructlab/issues/1637

We can do the doc update as a separate PR or part of this.

**Comment by booxter** [comment]
> Is there a ticket for Intel Mac support?

@tiran only the PyTorch one that I already linked to. I can report one. Q: Do you think we should add another CI job that would use the x86_64 macosx worker instead of arm64?

**Review by RobotSail — APPROVED** [review]
LGTM

**Review by booxter — APPROVED** [review]

**Pull request merged**
