### PR TITLE
Intel Gaudi / Habana Labs HPU support

### PR DESCRIPTION
**Pull request by tiran**
# Changes

**Which issue is resolved by this Pull Request:**
See #965

**Description of your changes:**

Initial implementation of training with Intel Gaudi devices. HPU support is experimental and training code is not yet optimized for Gaudi hardware.

- allow `ilab train --device=hpu`
- import `habana_framework` to register `hpu` device support
- update `requirements.txt` to allow older versions for Python 3.10. The
  Habana Labs stack comes with custom builds of Torch 2.2.0a0.
- add optional dependencies `instructlab[habana]` with fork of
  `optimum-habana` package.
- document Habana Labs software stack installation
- container file based on Habana Lab's RHEL 9.2 / Habana 1.15.1 container image (as of today the latest release)

### CODE REVIEW

**Comment by tiran** [comment]
PR depends on #957

**Comment by rhatdan** [comment]
If we can get this in, I can add it to the intel bootc container in ai-lab-recipes.

**Comment by tiran** [comment]
We need somebody to review the PR. I can address feedback tomorrow morning Central European Time.

**Comment by russellb** [comment]
lgtm since it seems very low risk for other platforms.

I wanted to run the e2e job first: https://github.com/instructlab/instructlab/actions/runs/8973129491

The job tests with cuda, so it should at least help validate that workflow is still good

**Review by russellb — APPROVED** [review]
e2e still passes, so lgtm

**Comment by russellb** [comment]
This appeared to break CI, so I had to revert it in #1122 

Here is the failure after it merged to main. I'm guessing we would have seen it here if we had rebased this PR to test against the latest. 

https://github.com/instructlab/instructlab/actions/runs/8973622978/job/24644228278

**Pull request merged**
