### PR TITLE
fix: remove unused flag from e2e job configs

### PR DESCRIPTION
**Pull request by nathan-weinberg**
the 'c' flag is no longer used by the e2e test
script - left it in as this script is used in
other repos but removed it from all the jobs
defined here

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by leseb — COMMENTED** [review]
If not used should remove it from `basic-workflow-tests.sh` too?

**Review by russellb — APPROVED** [review]
We should probably just remove `-m` too and make that the default behavior. I don't think we run anywhere without it anyway.

**Comment by russellb** [comment]
> If not used should remove it from `basic-workflow-tests.sh` too?

other repos probably still reference it. I would leave it a while longer unless someone wants to go through all repos to check -- sdg, eval in particular

**Comment by nathan-weinberg** [comment]
> > If not used should remove it from `basic-workflow-tests.sh` too?
> 
> other repos probably still reference it. I would leave it a while longer unless someone wants to go through all repos to check -- sdg, eval in particular

Still used in SDG:
- https://github.com/instructlab/sdg/blob/main/.github/workflows/e2e.yml
- https://github.com/instructlab/sdg/blob/main/.github/workflows/e2e-nvidia-a10g-x4.yml

Eval I'm removing it as part of https://github.com/instructlab/eval/pull/71

**Review by RobotSail — APPROVED** [review]
LGTM

**Pull request merged**
