### PR TITLE
Use schema repository via submodule

### PR DESCRIPTION
**Pull request by bjhargrave**
# Changes

**Which issue is resolved by this Pull Request:**
Partial #760

**Description of your changes:**

This avoids the need to duplicate the schema files in this repository.

Also, since the taxonomy repo now uses submodules, we want to clone the
complete view of the repo.

### CODE REVIEW

**Comment by tiran** [comment]
Could you please mention submodules in the README? Contributors now have to clone the project with `git clone --recurse-submodules` or fetch the submodules afterwards. They have to pull and update the submodule every time it is moved to a new commit, e.g. `git pull --recurse-submodules` or `git submodule update`.

**Comment by nathan-weinberg** [comment]
Looks like this needs rebase - is there anything else needed for this PR before merging?

**Comment by bjhargrave** [comment]
> Looks like this needs rebase

Done!

**Review by hickeyma — APPROVED** [review]
LGTM, thanks @bjhargrave

**Pull request merged**
