### PR TITLE
removed What's New? section in README.md (issue #2187)

### LINKED ISSUE #2187: Update or remove `What's New?` section in `README.md`
This section is out-of-date: https://github.com/instructlab/instructlab?tab=readme-ov-file#-whats-new

Should be updated or removed (not sure what the original motivation here was)

### PR DESCRIPTION
**Pull request by coson-lu**
**Issue resolved by this Pull Request: Removed What's New? section in README.md as the section is out-of-date**
Resolves #2187

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by leseb — COMMENTED** [review]
Please add a sign-off to your commit, see DCO error. Thanks!

**Comment by nathan-weinberg** [comment]
Thanks @coson-lu!

Can you squash the merge commit? Once done this should be good for merge!

**Comment by coson-lu** [comment]
Did I squash the merge commit correctly?

**Comment by nathan-weinberg** [comment]
> Did I squash the merge commit correctly?

Nope, there are three commits now, please squash down to a single signed commit

**Comment by coson-lu** [comment]
Sorry, I accidently messed up the branches. I will close this commit, delete this branch, and start over.

**Pull request closed without merging**
