### PR TITLE
update the MacOS bash completion note

### PR DESCRIPTION
**Pull request by reidliu41**
There are some issues when used `bash completion` in `MacOS`, so try to improve the doc

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Functional tests have been added, if necessary.
- [ ] E2E Workflow tests have been added, if necessary.

### CODE REVIEW

**Comment by reidliu41** [comment]
```
$ /bin/bash --version
GNU bash, version 3.2.57(1)-release  # default version

$ which bash
/opt/homebrew/bin/bash
$ bash --version
GNU bash, version 5.2.32(1)-release

$ cat /etc/shells
/bin/bash
/bin/csh
/bin/dash
/bin/ksh
/bin/sh
/bin/tcsh
/bin/zsh
/opt/homebrew/bin/bash  ## newer version

$ echo $SHELL
/bin/bash             # still using the old shell to login
$ eval "$(_ILAB_COMPLETE=bash_source ilab)"
-bash: complete: nosort: invalid option name  # not support nosort

$ bash
$(_ILAB_COMPLETE=bash_source ilab)"
```

**Review by nathan-weinberg — APPROVED** [review]

**Comment by reidliu41** [comment]
hi guys, feel free to share ideas.

**Review by bjhargrave — COMMENTED** [review]
zsh is the default shell on macOS (for several releases now). So I am not sure this bash note will apply to many/any Mac users. They also will likely not know how to update bash anyway :-)

**Review by RobotSail — APPROVED** [review]
LGTM

**Comment by reidliu41** [comment]
> zsh is the default shell on macOS (for several releases now). So I am not sure this bash note will apply to many/any Mac users. They also will likely not know how to update bash anyway :-)

Thanks for your feedback, yeah, maybe just for some bash user, like myself, test with RHEL every day, so get used to bash, so my first action is change the shell to bash when I got the Mac...

**Pull request merged**
