### PR TITLE
deps: Bump min eval version to 0.0.4

### LINKED ISSUE #1542: Every `ilab` invokation or import make a HTTPS call, `ilab` breaks without internet
**Describe the bug**

I noticed that a recent change in InstructLab introduced a very problematic behavior. All import of `instructlab.lab` and therefore all `ilab` calls make a HTTPS connection to Hugging Face Hub. Even `ilab --help` behaves that way. Even worse, it is no longer possible to run `ilab` without an internet connection, unless a previous call has populated a cache.

**To Reproduce**
* install `instructlab` in a virtual environment
* run `XDG_CACHE_HOME=$(pwd)/cache unshare -rn ilab --help`

`XDG_CACHE_HOME=$(pwd)/cache` sets the cache root to a new, empty directory. `unshare -rn` creates a new network namespace without access to the internet.

**Expected behavior**
InstructLab should work without a network connection and not dial home for every call.

**Screenshots**
```
$ XDG_CACHE_HOME=$(pwd)/cache unshare -rn ilab --help
[2024-07-01 07:03:27,681] [WARNING] [real_accelerator.py:162:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
[2024-07-01 07:03:27,691] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cpu (auto detect)
Traceback (most recent call last):
  File ".tox/py311-unit/bin/ilab", line 5, in <module>
    from instructlab.lab import ilab
  File ".tox/py311-unit/lib/python3.11/site-packages/instructlab/lab.py", line 18, in <module>
    from .model import model as model_group
  File ".tox/py311-unit/lib/python3.11/site-packages/instructlab/model/model.py", line 11, in <module>
    from .evaluate import evaluate
  File ".tox/py311-unit/lib/python3.11/site-packages/instructlab/model/evaluate.py", line 8, in <module>
    from instructlab.eval.mmlu import MMLUBranchEvaluator, MMLUEvaluator
  File ".tox/py311-unit/lib/python3.11/site-packages/instructlab/eval/mmlu.py", line 7, in <module>
    from lm_eval.evaluator import simple_evaluate  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".tox/py311-unit/lib/python3.11/site-packages/lm_eval/__init__.py", line 1, in <module>
    from .evaluator import evaluate, simple_evaluate
  File ".tox/py311-unit/lib/python3.11/site-packages/lm_eval/evaluator.py", line 11, in <module>
    import lm_eval.api.metrics
  File ".tox/py311-unit/lib/python3.11/site-packages/lm_eval/api/metrics.py", line 168, in <module>
    exact_match = hf_evaluate.load("exact_match")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".tox/py311-unit/lib/python3.11/site-packages/evaluate/loading.py", line 748, in load
    evaluation_module = evaluation_module_factory(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".tox/py311-unit/lib/python3.11/site-packages/evaluate/loading.py", line 681, in evaluation_module_factory
    raise FileNotFoundError(
FileNotFoundError: Couldn't find a module script at exact_match/exact_match.py. Module 'exact_match' doesn't exist on the Hugging Face Hub either.
```

**Device Info (please complete the following information):**
instructlab               0.17.1.dev221
instructlab-eval          0.0.3

**Additional context**

### PR DESCRIPTION
**Pull request by nathan-weinberg**
**Issue resolved by this Pull Request:**
Resolves #1542 

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by alimaredia — APPROVED** [review]
@nathan-weinberg Maybe we put a hold on this PR until you give us the heads up when the updated version of the eval library is released?

**Comment by nathan-weinberg** [comment]
@alimaredia it is released

**Comment by nathan-weinberg** [comment]
@RobotSail @Maxusmusti hey fellas not sure why I'm getting a training failure on this PR any idea?

**Comment by tiran** [comment]
@nathan-weinberg There is also a new release of instructlab-training. The latest release makes `run_training` a dynamic attribute, so we don't pull `torch`. PyLint is not clever enough.

**Review by tiran — APPROVED** [review]

**Comment by nathan-weinberg** [comment]
Since the lint failure is unrelated to this PR and all other checks have passed, I'm going to merge this manually

**Pull request merged**
