### PR TITLE
ilab init set default to "yes" for cloning down taxonomy if not existing

### LINKED ISSUE #1547: ilab init should default to "yes" for cloning down taxonomy if not existing
when running `ilab init`. it will ask to download the taxonomy from git if its not already there,  the default response is no.  We should default to YES to improve the new user experience.  (also the repeat user who just blindly hits "enter" every time, not naming any names @jjasghar).

in my opinion this will help the new user experience.

### PR DESCRIPTION
**Pull request by chudegao**
**Issue resolved by this Pull Request:**
Resolves #1547

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by tiran — CHANGES_REQUESTED** [review]
Please update test tests under `tests_lab_init`, too.

- add mock to all interactive test functions
- verify that the default value clones the repo

**Review by danmcp — APPROVED** [review]

**Review by nathan-weinberg — APPROVED** [review]

**Comment by nathan-weinberg** [comment]
@chudegao can you rebase?

**Comment by chudegao** [comment]
> @chudegao can you rebase?

Done

**Comment by nathan-weinberg** [comment]
@tiran can you re-review when you get a chance?

**Comment by nathan-weinberg** [comment]
@Mergifyio rebase

**Review by khaledsulayman — APPROVED** [review]

**Pull request merged**
