### PR TITLE
split `ilab model serve` click cmds from functionality

### PR DESCRIPTION
**Pull request by alinaryan**
Refactored click command handling into a dedicated `cli` module and moved the core serve functionality into a separate module. This restructing lays the groundwork for future API handlers and multi-processing work.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Functional tests have been added, if necessary.
- [ ] E2E Workflow tests have been added, if necessary.

### CODE REVIEW

**Review by jaideepr97 — COMMENTED** [review]
@alinaryan it might be better if `cli/model/serve.py` showed up as a 'rename' rather than a new addition 
This would show a more accurate version of the diff of what has changed - currently it says the whole file has changed because its a 'new addition'

the way to do this would be:
- make a copy of your current `cli/model/serve.py` file somewhere 
- delete it 
- restore `src/instructlab/model/serve.py
- perform `git mv src/instructlab/model/serve.py src/instructlab/cli/model/serve.py` 
- overwrite `src/instructlab/model/serve.py` with your saved copy to get back your changes
- push 

I think this will ensure this file shows up as a rename and the diff shows what actually changed in the file other than being moved

**Comment by jaideepr97** [comment]
also please take a look at the failing unit tests
should be a quick fix!

**Comment by alinaryan** [comment]
>@alinaryan it might be better if cli/model/serve.py showed up as a 'rename' rather than a new addition
This would show a more accurate version of the diff of what has changed - currently it says the whole file has changed because its a 'new addition'

@jaideepr97 discussed offline, but tried this workflow a few different ways and the diff result was the same each time

**Review by jaideepr97 — APPROVED** [review]
thanks @alinaryan

**Review by nathan-weinberg — APPROVED** [review]

**Comment by nathan-weinberg** [comment]
@Mergifyio refresh

**Pull request merged**
