### PR TITLE
Update A100_H100_x4 to slightly lower max_batch_len (55000->54000)

### PR DESCRIPTION
**Pull request by Maxusmusti**
Turns out there are edge cases where exactly 55k breaks, 54k should be fully safe

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by leseb — COMMENTED** [review]
Can you add more rationale about that choice so that others can benefit from it :). Thanks!

**Comment by Maxusmusti** [comment]
@leseb Yeah sure, essentially with training, we have found that the maximum value we can push that `max_batch_len` field to without the chance of hitting an OOM lies somewhere between 54k and 55k. A batch with a size above that value will overflow an 80GB card (in a 4x scenario) and crash with an OOM. Anything below that value should be within 80GB. Originally we thought that cut-off was 55k, but we realized it was slightly lower, so adjusting accordingly.

**Comment by leseb** [comment]
> @leseb Yeah sure, essentially with training, we have found that the maximum value we can push that `max_batch_len` field to without the chance of hitting an OOM lies somewhere between 54k and 55k. A batch with a size above that value will overflow an 80GB card (in a 4x scenario) and crash with an OOM. Anything below that value should be within 80GB. Originally we thought that cut-off was 55k, but we realized it was slightly lower, so adjusting accordingly.

This is very helpful thank you. Could you please include this in your commit message? Thanks!

**Comment by Maxusmusti** [comment]
@leseb done

**Review by leseb — APPROVED** [review]
Next time if you can wrap the commit body to 72 char that would be great :), thanks!

**Review by nathan-weinberg — APPROVED** [review]

**Pull request merged**
