### PR TITLE
HOLD: Add support for custom CA bundles in SDG process

### PR DESCRIPTION
**Pull request by relyt0925**
**Issue resolved by this Pull Request:**
Resolves https://github.com/instructlab/instructlab/issues/1647

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by relyt0925** [comment]
Believe for this to have an impact: we need an updated sdg tag published to pypi and the requirements.txt updated

**Comment by relyt0925** [comment]
Happy path of CA cert
```
[root@rhel-ai-sdg-training-client-1 instructlabbigdisk]# ilab generate --taxonomy-path taxonomy/compositional_skills/extraction/email/markdown/qna.yaml --endpoint-url https://781d2e7c-us-east.lb.appdomain.cloud/v1 --model-family mixtral --num-instructions 1 --model /instructlab/models/mistralai/Mixtral-8x7B-Instruct-v0.1 --tls-ca-bundle teachermodel.crt 
ilab generate --taxonomy-path taxonomy/compositional_skills/extraction/email/markdown/qna.yaml --endpoint-url https://781d2e7c-us-east.lb.appdomain.cloud/v1 --model-family mixtral --num-instructions 1 --model /instructlab/models/mistralai/Mixtral-8x7B-Instruct-v0.1 --tls-ca-bundle teachermodel.crt --model /instructlab/models/mistralai/Mixtral-8x7B-Instruct-v0.1
You are using an aliased command, this will be deprecated in a future release. Please consider using `ilab data generate` instead
INFO 2024-07-10 01:39:40,296 utils.py:145: _init_num_threads Note: detected 80 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
INFO 2024-07-10 01:39:40,296 utils.py:148: _init_num_threads Note: NumExpr detected 80 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 16.
INFO 2024-07-10 01:39:40,296 utils.py:161: _init_num_threads NumExpr defaulting to 16 threads.
INFO 2024-07-10 01:39:40,483 config.py:58: <module> PyTorch version 2.3.1 available.
Generating synthetic data using '/instructlab/models/mistralai/Mixtral-8x7B-Instruct-v0.1' model, taxonomy:'taxonomy/compositional_skills/extraction/email/markdown/qna.yaml' against https://781d2e7c-us-east.lb.appdomain.cloud/v1 server
INFO 2024-07-10 01:39:41,145 generate_data.py:266: generate_data Synthesizing new instructions. If you aren't satisfied with the generated instructions, interrupt training (Ctrl-C) and try adjusting your YAML files. Adding more examples may help.
INFO 2024-07-10 01:39:41,155 pipeline.py:48: generate Running block: gen_skill_grounded
INFO 2024-07-10 01:39:41,155 pipeline.py:49: generate Dataset({
    features: ['task_description', 'seed_context', 'seed_question', 'seed_response'],
    num_rows: 3
})
INFO 2024-07-10 01:39:48,014 generate_data.py:294: generate_data Generated 1 samples
INFO 2024-07-10 01:39:48,015 generate_data.py:312: generate_data Generation took 6.90s
[root@rhel-ai-sdg-training-client-1 instructlabbigdisk]# 
```

**Comment by relyt0925** [comment]
Showing it fails without specifying the TLS ca (valid as it's signed by private CA)
```
[root@rhel-ai-sdg-training-client-1 instructlabbigdisk]# ilab generate --taxonomy-path taxonomy/compositional_skills/extraction/email/markdown/qna.yaml --endpoint-url https://781d2e7c-us-east.lb.appdomain.cloud/v1 --model-family mixtral --num-instructions 1 --model /instructlab/models/mistralai/Mixtral-8x7B-Instruct-v0.1 
ilab generate --taxonomy-path taxonomy/compositional_skills/extraction/email/markdown/qna.yaml --endpoint-url https://781d2e7c-us-east.lb.appdomain.cloud/v1 --model-family mixtral --num-instructions 1 --model /instructlab/models/mistralai/Mixtral-8x7B-Instruct-v0.1 --model /instructlab/models/mistralai/Mixtral-8x7B-Instruct-v0.1
You are using an aliased command, this will be deprecated in a future release. Please consider using `ilab data generate` instead
INFO 2024-07-10 01:40:27,293 utils.py:145: _init_num_threads Note: detected 80 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
INFO 2024-07-10 01:40:27,293 utils.py:148: _init_num_threads Note: NumExpr detected 80 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 16.
INFO 2024-07-10 01:40:27,293 utils.py:161: _init_num_threads NumExpr defaulting to 16 threads.
INFO 2024-07-10 01:40:27,479 config.py:58: <module> PyTorch version 2.3.1 available.
Generating synthetic data using '/instructlab/models/mistralai/Mixtral-8x7B-Instruct-v0.1' model, taxonomy:'taxonomy/compositional_skills/extraction/email/markdown/qna.yaml' against https://781d2e7c-us-east.lb.appdomain.cloud/v1 server
INFO 2024-07-10 01:40:28,169 generate_data.py:266: generate_data Synthesizing new instructions. If you aren't satisfied with the generated instructions, interrupt training (Ctrl-C) and try adjusting your YAML files. Adding more examples may help.
INFO 2024-07-10 01:40:28,179 pipeline.py:48: generate Running block: gen_skill_grounded
INFO 2024-07-10 01:40:28,179 pipeline.py:49: generate Dataset({
    features: ['task_description', 'seed_context', 'seed_question', 'seed_response'],
    num_rows: 3
})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 154, in _connect
    stream = stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 152, in start_tls
    with map_exceptions(exc_map):
  File "/usr/lib64/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 978, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib64/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/ilab", line 8, in <module>
    sys.exit(ilab())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/instructlab/utils.py", line 551, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/instructlab/data/generate.py", line 202, in generate
    generate_data(
  File "/usr/local/lib/python3.11/site-packages/instructlab/sdg/generate_data.py", line 288, in generate_data
    new_generated_data = sdg.generate(ds)
                         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/instructlab/sdg/sdg.py", line 19, in generate
    dataset = pipeline.generate(dataset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/instructlab/sdg/pipeline.py", line 51, in generate
    dataset = block.generate(dataset, **gen_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/instructlab/sdg/iterblock.py", line 23, in generate
    batch_generated = self.block.generate(
                      ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/instructlab/sdg/llmblock.py", line 123, in generate
    outputs = [self._generate([sample], **gen_kwargs)[0] for sample in samples]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/instructlab/sdg/llmblock.py", line 123, in <listcomp>
    outputs = [self._generate([sample], **gen_kwargs)[0] for sample in samples]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/instructlab/sdg/llmblock.py", line 94, in _generate
    response = self.client.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/resources/completions.py", line 528, in create
    return self._post(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1266, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 942, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1002, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1079, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1002, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1079, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1012, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
```

**Comment by relyt0925** [comment]
tls_insecure still works
```
ilab generate --taxonomy-path taxonomy/compositional_skills/extraction/email/markdown/qna.yaml --endpoint-url https://781d2e7c-us-east.lb.appdomain.cloud/v1 --model-family mixtral --num-instructions 1 --model /instructlab/models/mistralai/Mixtral-8x7B-Instruct-v0.1 --tls-insecure --model /instructlab/models/mistralai/Mixtral-8x7B-Instruct-v0.1
You are using an aliased command, this will be deprecated in a future release. Please consider using `ilab data generate` instead
INFO 2024-07-10 01:41:49,866 utils.py:145: _init_num_threads Note: detected 80 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
INFO 2024-07-10 01:41:49,866 utils.py:148: _init_num_threads Note: NumExpr detected 80 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 16.
INFO 2024-07-10 01:41:49,866 utils.py:161: _init_num_threads NumExpr defaulting to 16 threads.
INFO 2024-07-10 01:41:50,061 config.py:58: <module> PyTorch version 2.3.1 available.
Generating synthetic data using '/instructlab/models/mistralai/Mixtral-8x7B-Instruct-v0.1' model, taxonomy:'taxonomy/compositional_skills/extraction/email/markdown/qna.yaml' against https://781d2e7c-us-east.lb.appdomain.cloud/v1 server
INFO 2024-07-10 01:41:50,741 generate_data.py:266: generate_data Synthesizing new instructions. If you aren't satisfied with the generated instructions, interrupt training (Ctrl-C) and try adjusting your YAML files. Adding more examples may help.
INFO 2024-07-10 01:41:50,751 pipeline.py:48: generate Running block: gen_skill_grounded
INFO 2024-07-10 01:41:50,752 pipeline.py:49: generate Dataset({
    features: ['task_description', 'seed_context', 'seed_question', 'seed_response'],
    num_rows: 3
})
INFO 2024-07-10 01:42:00,856 generate_data.py:294: generate_data Generated 1 samples
INFO 2024-07-10 01:42:00,857 generate_data.py:312: generate_data Generation took 10.14s
[root@rhel-ai-sdg-training-client-1 instructlabbigdisk]# 
```

**Comment by russellb** [comment]
> Believe for this to have an impact: we need an updated sdg tag published to pypi and the requirements.txt updated

That's right. This PR should have `instructlab-sdg>=0.1.1` in requirements.txt, and then we'll have to hold it until another sdg release is made that includes the feature

**Comment by tiran** [comment]
You do not need an option to set a custom CA store. This can be archived with `SSL_CERT_FILE` env var.

https://www.python-httpx.org/environment_variables/

**Review by tiran — CHANGES_REQUESTED** [review]
I recommend to drop this change and instead document `SSL_CERT_FILE` env var. It is the standard way to configure any OpenSSL-based client to use a custom CA cert file. Python's ssl module and httpx client use this env var.

**Comment by relyt0925** [comment]
@tiran the thing I would note (at least in the context of RHEL AI: these processes are launched as containers and there is no process today in the "wrapper automation" to scan for environment variables passed into the script and then pass them to the host. To me also: that seems odd and we would want all the commands driven through CLI flags but happy to follow whatever direction the community thinks is best.

**Comment by relyt0925** [comment]
example of the ilab RHEL AI read only process on RHEL AI

```
#!/bin/bash

# Template values replaced by container build
ENDPOINT_URL="http://0.0.0.0:8080/v1"
TRAIN_DEVICE="cuda"
CONTAINER_DEVICE="nvidia.com/gpu=all"
IMAGE_NAME="icr.io/sps-instrctlab/instructlab-nvidia:latest"
VLLM_NAME="icr.io/sps-instrctlab/vllm:latest"
TRAIN_NAME="icr.io/sps-instrctlab/deepspeed-trainer:latest"
GPU_COUNT_COMMAND="nvidia-ctk --quiet cdi list | grep -P nvidia.com/gpu='\d+' | wc -l"

# ENDPOINT_URL="http://0.0.0.0:8080/v1"
# TRAIN_DEVICE="cuda"
# CONTAINER_DEVICE="nvidia.com/gpu=all"
# IMAGE_NAME="quay.io/ai-lab/instructlab-nvidia:latest"
# VLLM_NAME="quay.io/ai-lab/vllm:latest"
# TRAIN_NAME="quay.io/ai-lab/deepspeed-trainer:latest"
# GPU_COUNT_COMMAND="nvidia-ctk --quiet cdi list | grep -P nvidia.com/gpu='\d+' | wc -l"

# HF caching uses relative symlink structures, so keep cache relative to
# the central working directory
CONTAINER_CACHE="/instructlab/cache"
HOST_CACHE="$(pwd)/cache"
WORKDIR="$(pwd)"
SCRIPT_DIR=$(dirname "$0")
DEFAULT_SERVE_MODEL="mistralai/Mixtral-8x7B-Instruct-v0.1"

if [[ -z "${GPU_AMOUNT}" ]]; then
	GPU_AMOUNT=$(bash -c "${GPU_COUNT_COMMAND}")
	if [[ "$?" != "0" ]]; then
		echo "Could not determine GPU count, set export GPU_AMOUNT= manually"
		exit
	fi
fi

if [[ "$GPU_AMOUNT" -le 2 ]]; then
	echo "WARNING: You need at least 2 GPUs to load full precision models"
fi

NPROC_PER_NODE=${GPU_AMOUNT}
EFFECTIVE_BATCH_SIZE=$((12*${GPU_AMOUNT}))
NUM_INSTRUCTIONS=5000
NUM_EPOCHS=10

has_argument() {
	match=$1
	shift
	for arg in "$@"; do
		if [[ "$arg" == *"$match"* ]]; then
			return 0
		fi
	done
	return 1
}

get_argument() {
	local match=$1
	shift

	local found=false
	local arg
	while [ "$#" -gt 0 ]; do
		arg="$1"
		shift
		if [[ "$arg" == "$match" ]]; then
			found=true
			if [ "$#" -gt 0 ]; then
				echo "$1"
				return 0
			else
				echo ""
				return 0
			fi
		fi
	done

	if ! $found; then
		echo ""
		return 0
	fi
}

get_argument_default() {
	local match=$1
	local default=$2
	shift
	shift
	local result=$(get_argument ${match} "$@")
	if [[ -z "${result}" ]]; then
		echo $default
		return 0
	fi
	echo "${result}"
}

get_model() {
	model=$(get_argument_default "--model" "${DEFAULT_SERVE_MODEL}" "$@")
	if [[ ! "${model}" =~ ^/instructlab/models.* ]]; then
		echo /instructlab/models/"${model}"
	else
		echo "${model}"
	fi
}

mkdir -p "${HOST_CACHE}"
PODMAN_COMMAND=("podman" "run" "--rm" "-it" "--device" "${CONTAINER_DEVICE}" \
		"--security-opt" "label=disable" "--net" "host" \
		"-v" "${WORKDIR}:/instructlab" "--entrypoint" "" \
		"-e" "HF_HOME=${CONTAINER_CACHE}" \
		"-e" "HF_TOKEN=${HF_TOKEN}" \
		"${IMAGE_NAME}")
PODMAN_COMMAND_SERVE=("podman" "run" "--rm" "-it" "--device" "${CONTAINER_DEVICE}" \
		"--security-opt" "label=disable" "--net" "host" \
		"-v" "${WORKDIR}:/instructlab" \
		"--shm-size=10gb" \
		"-e" "HF_HOME=${CONTAINER_CACHE}/" \
		"-e" "HF_TOKEN=${HF_TOKEN}" \
		"${VLLM_NAME}" "--host=0.0.0.0" "--port=8080" "--tensor-parallel-size=${GPU_AMOUNT}")

if [[ "$1" = "init" ]]; then
	if ! has_argument "--repository" "$@"; then
		shift
		"${PODMAN_COMMAND[@]}" ilab init \
			--repository https://github.com/instructlab/taxonomy.git "$@"
		exit $?
	fi
elif [[ "$1" = "train" ]]; then
	samples=$(get_argument_default "--num-samples" ${NUM_INSTRUCTIONS} "$@")
	epochs=$(get_argument_default "--num-epochs" ${NUM_EPOCHS} "$@")
	${SCRIPT_DIR}/ilab-training-launcher ${NPROC_PER_NODE} ${EFFECTIVE_BATCH_SIZE} \
		${TRAIN_DEVICE} ${samples} ${epochs} ${CONTAINER_DEVICE} ${TRAIN_NAME}
	exit $?
elif [[ "$1" = "serve" ]]; then
	# run vllm container which will serve vllm and ilab generate
	args=()
	model=$(get_model "$@")
	if [[ "${model}" == *"${DEFAULT_SERVE_MODEL}" ]]; then
		args+=("--chat-template=mixtral.jinja")
	fi
	args+=("--model" "${model}")
	"${PODMAN_COMMAND_SERVE[@]}" "${args[@]}"
	exit $?
elif [[ "$1" = "chat" ]]; then
	shift
	args=($@)
	if ! has_argument "--endpoint-url" "$@"; then
		args+=("--endpoint-url" "http://0.0.0.0:8080/v1")
	fi
	if ! has_argument "--model-family" "$@"; then
		args+=("--model-family" "mixtral")
	fi
	args+=("--model" $(get_model "$@"))
	"${PODMAN_COMMAND[@]}" ilab chat "${args[@]}"
	exit $?
elif [[ "$1" = "generate" ]]; then
	shift
	args=($@)
	if ! has_argument "--endpoint-url" "$@"; then
		args+=("--endpoint-url" "http://0.0.0.0:8080/v1")
	fi
	if ! has_argument "--model-family" "$@"; then
		args+=("--model-family" "mixtral")
	fi
	if ! has_argument "--num-instructions" "$@"; then
		args+=("--num-instructions" "5000")
	fi
	args+=("--model" $(get_model "$@"))
	echo ilab generate "${args[@]}"

	"${PODMAN_COMMAND[@]}" ilab generate "${args[@]}"
	exit $?
elif [[ "$1" == "download" && $# -lt 2 ]]; then
	echo "You must specify the model to download."
	echo
	echo "High-fidelity generation and training requires two models:"
	echo
	echo "Mixtral: ilab download --repository ${DEFAULT_SERVE_MODEL}"
	echo "Granite: ilab download --repository ibm/granite-7b-base"
	echo
	echo "For more options type ilab --help"
	exit 1
fi

"${PODMAN_COMMAND[@]}" ilab "$@"
```

**Comment by relyt0925** [comment]
One other thing to note as well: I'm not sure if you did it in that manner: that you would then also override the CA bundle for *all* processes (I think right now the main one is git fetching) which likely want to keep the default bundle or have a way to be pointed to a bundle specific to it's process only.

**Comment by tiran** [comment]
- The easist way to use a custom CA trust store in a process is to use `SSL_CERT_FILE` and `SSL_CERT_DIR` env var.
- For a container, it's better to mount-bind a CA cert file into the container and then use an entry-point script to inject the certificate into the system trust store. That's a simple copy + `update-ca-trust` on Fedora/RHEL-based systems.

> One other thing to note as well: I'm not sure if you did it in that manner: that you would then also override the CA bundle for _all_ processes (I think right now the main one is git fetching) which likely want to keep the default bundle or have a way to be pointed to a bundle specific to it's process only.

Yes, that is the expected outcome of an option like `--tls-ca-bundle`. Everything else would be surprising behavior and a potential security bug. If a user tells a program to use a custom trust store, then the program should not trust any other CA certificate.

Is there a ticket or design document that explains why this option is required in the first place and what the expected behavior of the option is?

Background: I was the primary maintainer of Python's `ssl` for over a decade. Before I joined RHEL AI, I worked in Red Hat's security engineering and identity management department on FreeIPA (RHEL IdM), Dogtag (Red Hat Certificate System), and related topics for 9 years.

**Comment by relyt0925** [comment]
The context (I originally submitted the pr to both sdg and then this option): is right now on RHEL AI when I was working with it: there is not a path to be able to utilize a custom CA for certificates for SDG when talking to the teacher model (was running in a mode where there are a pool of teacher models behind a private load balancer that SDG then reaches out to talk to to do synthetic data generation). I don't think I opened up an issue detailing that problem though and can do so!

**Comment by relyt0925** [comment]
Something like this command for example:
```
ilab generate --taxonomy-path taxonomy/compositional_skills/STEM/science/units_conversion/temperature_conversion/qna.yaml --endpoint-url https://781d2e7c-us-east.lb.appdomain.cloud/v1 --model-family mixtral --num-instructions 100 --model /instructlab/models/mistralai/Mixtral-8x7B-Instruct-v0.1
```

Where `https://781d2e7c-us-east.lb.appdomain.cloud/v1` is a load balancer that points to a pool of RHEL AI machines running a "teacher model" preloaded that can be utilized for SDG. Effectively to do that now: you either need to have certificates issued that are from a public provider (like Let's Encrypt) or if you are using a private CA for the certs you have to run with tls-insecure based on the current parameters that are available in the ilab wrapper script for RHEL AI

**Comment by tiran** [comment]
Let me try to generate a use case from your feedback:

> As an InstructLab user, I want to use an internal OpenAI server endpoint for `ilab data generate` and `ilab model chat`. The internal OpenAI uses HTTPS with a private root CA certificate. I need an way to tell InstructLab that it can trust my private CA for communication with my OpenAI server.

Did I get it right?

**Comment by relyt0925** [comment]
Yes that was a perfect summary!

**Comment by tiran** [comment]
Excellent! Now we have a mutual understanding of the problem.

Since you have to touch the signature sdg's `generate_data()` function anyway, I suggest to radically improve and simplify the signature. It still has the old kitchen-sink signature from the time it was part of InstructLab core.

- remove `api_base`, `api_key`, and all `tls_` parameters and replace it with a single `openai_client: openai.OpenAI` parameter.
- then change `instructlab.data.generate` to create an `openai.OpenAI` object and pass it to `generate_data`. This replaces 7 parameters (6 old plus your new CA param) with a single object. It separates configuration from usage, too.
- while you are on it, could you please replace the `logger` argument with a module-level `logger = logging.getLogger(__name__)` logger? We fixed most places a two, three weeks ago. `generate_data` is one of the few places that uses the outdated logger parameter.

I also suggest to rename the parameters to reflect their purpose. The names `--tls-client-cert` and `--tls-ca-bundle` are too technical (TLS, bundle) and do not explain the affect on the program. How about `--endpoint-client-cert`, `--endpoint-ca-cert`, and so on? It makes it obvious that the options affect `--endpoint-url` parameter.

If you like the idea, then we can share the work. If you would take care of `instructlab.sdg`, then I can improve `instructlab` core for you.

**Comment by relyt0925** [comment]
Yea I would love to help push the project forward for full disclosure: I am on the IBM Cloud team looking to implement a managed service version of the instructlab apis (all executed through a fleet of RHEL AI machines). I just want to make sure at this phase of the game @russellb is also ok with someone potentially external to Red Hat driving those changes (and any other key maintainer of the sdg side of the house). But if y'all are ok with that at this phase of the project I am excited to help out!

**Comment by russellb** [comment]
I'm generally happy with the direction proposed by @tiran.  Indeed, `generate_data()` was carried over as-is to make the transition to the sdg library a bit quicker. At some point having a "do everything" entrypoint into the library should go away. 

Adding parameters to `generate_data()` is easy enough, but removing them breaks backwards compatibility with the previous versions of `ilab` that only have a minimum version required for `instructlab-sdg`.

I kind of wonder if we should just keep working on cleaning up the inside of `generate_data()` to the point where we can eventually make `ilab` no longer use it, and then at some point in the future drop the `generate_data()` wrapper, just to ease the transition a bit.

as for the immediate need, I'd propose just adding the option of passing in the openai client, but leave the rest for compatibility for the moment.

**Pull request closed without merging**
