### PR TITLE
ci: ensure $FULLTRAIN for 4xA10 workflow

### PR DESCRIPTION
**Pull request by alimaredia**
The 4xA10 workflow is intended to mirror the full ilab workflow. If `FULLTRAIN`  is set to `0` the final ilab chat and serve aren't run (https://github.com/instructlab/instructlab/blob/main/scripts/basic-workflow-tests.sh#L304). If the evaluation flag was specified in the future it would not be run as well.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by RobotSail — APPROVED** [review]
LGTM, I don't see why not.

**Review by khaledsulayman — APPROVED** [review]

**Comment by alimaredia** [comment]
@RobotSail or anyone else that's knowledgable, if we enable FULLTRAIN and the TRAIN_LIBRARY we won't hit the same issues as we see for the A10x1 instance with only FULLTRAIN right? 

This is a recent run I did of that
https://github.com/russellb/ilab-runner/actions/runs/10085943339/job/27887699505

**Comment by RobotSail** [comment]
@alimaredia Fulltrain works but only for the LoRA case since we aren't doing full model parallelism with DeepSpeed currently.

**Comment by RobotSail** [comment]
We would need to update how checkpointing works in the training library so we can split up the model and be able to run a full fine-tune.

**Comment by alimaredia** [comment]
Test to ensure the two training flags can go together is here: https://github.com/russellb/ilab-runner/actions/runs/10087870830/job/27892725725

**Comment by alimaredia** [comment]
@RobotSail looks like that last log failed during the training step. It only errored on serving because there was no model for `ilab model serve` to output.

**Comment by RobotSail** [comment]
@alimaredia I made a comment on that - you'll need to update the `--model-path` when serving so that it's pointing to the correct directory. We use temp directories in e2e while the config has it hard-coded to a specific dir. Therefore we need to just pass the correct path.

**Comment by nathan-weinberg** [comment]
@alimaredia where is this at?

**Comment by nathan-weinberg** [comment]
Superceded by https://github.com/instructlab/instructlab/pull/2291

**Pull request closed without merging**
