### PR TITLE
Revert "tests: Validate that null vllm_args are accepted"

### PR DESCRIPTION
**Pull request by cdoern**
Reverts instructlab/instructlab#2046

testing this to see if it fixes CI which is currently broken

### CODE REVIEW

**Comment by cdoern** [comment]
this fixes CI. @booxter PTAL if you have a chance

**Comment by nathan-weinberg** [comment]
Can we get some context here? This PR was passing CI when it was merged?

**Comment by booxter** [comment]
Yes please. Details / error message?

**Comment by cdoern** [comment]
@booxter the tests are failing here on main https://github.com/instructlab/instructlab/actions/runs/10476433131/job/29015300586 and also on any newly introduced PRs I think. Please correct me if I am wrong!

**Comment by danmcp** [comment]
Must have been a collision across multiple PRs?

**Comment by danmcp** [comment]
> Must have been a collision across multiple PRs?

Confirmed: This was broken with the combination of

https://github.com/instructlab/instructlab/pull/2092 and https://github.com/instructlab/instructlab/pull/2046

Both worked individually but don't work together.

I'll try and put together a fix for the test rather than reverting.

**Comment by danmcp** [comment]
Alternate fix: https://github.com/instructlab/instructlab/pull/2117

**Comment by nathan-weinberg** [comment]
Confirmed that https://github.com/instructlab/instructlab/pull/2117 fixed the issue - see that PR for runs

**Pull request closed without merging**
