### PR TITLE
Fixes incorrect file reference

### PR DESCRIPTION
**Pull request by RobotSail**
This PR fixes an issue where the training script currently uses the test files for both the training and the test files.

Signed-off-by: Oleg S <97077423+RobotSail@users.noreply.github.com>

### CODE REVIEW

**Review by cdoern — APPROVED** [review]

**Comment by russellb** [comment]
The change looks good -- it'd be great to call out what the impact was.  At a quick glance, it seems like it could be as bad as we weren't actually using the generated data for training.  Is it that bad?  Is it something else?

**Comment by RobotSail** [comment]
@russellb Yeah that's the case, but I think this was a minor thing that was overlooked in #1471 so it hasn't made it into a release yet.

**Review by russellb — APPROVED** [review]
sounds like the impact was more minimal that it originally looked.

This only affected new training using the library, and was correct until a change just a couple days ago.  all good.

**Comment by tiran** [comment]
Could [PyTorch training produces poor results consistenly](https://github.com/instructlab/instructlab/issues/1305) be related to this problem? Please create a ticket to remind us, that we must write unit/functional for the code block.

**Pull request merged**
