### PR TITLE
add repository and release option to the config

### PR DESCRIPTION
**Pull request by reidliu41**
**Checklist:**

In `download` sub-cmd, add the values of `--repository` and `--release` options to config
```
@click.command()
@click.option(
    "--repository",
    default=DEFAULTS.MERLINITE_GGUF_REPO,  # TODO: add to config.yaml
    show_default=True,
    help="Hugging Face or OCI repository of the model to download.",
)
@click.option(
    "--release",
    default="main",  # TODO: add to config.yaml
    show_default=True,
    help="The revision of the model to download - e.g. a branch, tag, or commit hash for Hugging Face repositories and tag or commit hash for OCI repositories.",
)

```

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Functional tests have been added, if necessary.
- [ ] E2E Workflow tests have been added, if necessary.

### CODE REVIEW

**Comment by reidliu41** [comment]
hi team, please feel free to take a look.thanks

**Comment by jaideepr97** [comment]
hi @reidliu41 
sorry about this, but would you mind rebasing? a change went in recently that allows us to accept multiple repositories and filenames during download now

**Comment by reidliu41** [comment]
@jaideepr97 updated

**Review by jaideepr97 — COMMENTED** [review]
Generally LGTM, thanks @reidliu41 ! 
I was wondering if you have thoughts about how to specify the list of filenames in the config 
I raised an issue around how filenames can/should be mapped to repositories when dealing with multi-model download
(https://github.com/instructlab/instructlab/issues/2490)

This is yet to be solved via the flags - i think this will also be an issue in the config

**Comment by reidliu41** [comment]
> Generally LGTM, thanks @reidliu41 ! I was wondering if you have thoughts about how to specify the list of filenames in the config I raised an issue around how filenames can/should be mapped to repositories when dealing with multi-model download (#2490)
> 
> This is yet to be solved via the flags - i think this will also be an issue in the config

Oh, thanks for your share. If need mapping, the config seems not work... May wait for your solution first.
Have you consider single situation with single arg e.g. --repository xx --filename xxx --release main
The multi-download with a new flag? e.g  -rfr <repository>:<filename>:<release>

**Comment by jaideepr97** [comment]
@reidliu41 in the config file, instead of grouping by release/repository etc, I would like to propose the following structure:

```
. . .
# Download configuration section.
download:
  models:
  -  repository: instructlab/merlinite-7b-lab-GGUF
      release: main
      filenames:
      -  merlinite-7b-lab-Q4_K_M.gguf
   - repository: TheBloke/Mistral-7B-Instruct-v0.2-GGUF
      release: main
      filenames:
      - mistral-7b-instruct-v0.2.Q5_0.gguf
   - repository: instructlab/granite-7b-lab
      release: main
 . . .
```

**Comment by nathan-weinberg** [comment]
In this scheme could you specify a GGUF repo w/o the filename @jaideepr97?

**Comment by williamcaban** [comment]
Can we consider adding a field on what to use the model for? (e.g. teacher model, etc)

**Comment by jaideepr97** [comment]
a new proposal that was made for this:

introduction of a dedicated `models` section in the config file that becomes the source of truth for all model information for the various models users can use - including some indication of what a given model is being used for (to @williamcaban's point )
The different sections such as `train`, `generate`, `chat` etc should reference a model from that section. The idea is to avoid duplication of model references so we don't end up in situations where the user forgets to update something in one place and does update it elsewhere expecting it to work

A couple of pre-requisites to make this possible:
- there is a discrepancy between what information will be stored in the models section, vs what information the various sections need to point to. The various components need to point to a local path to where the model is stored on disk. The models section has to be generic and capture a general reference to the model. In order to solve this discrepancy we must standardize around using the full model URL as the name and it should double up as the address of the model (local and remote) so that all parties referencing these fields will be satisfied. that requires implementation of https://github.com/instructlab/instructlab/issues/2358 
- This will be a breaking change to the config, and warrants bumping the config version to 2.0 - before we can make such a change we need to implement some kind of config management module to retain backward compatibility with previous config versions - https://github.com/instructlab/instructlab/issues/2334

**Comment by jaideepr97** [comment]
@reidliu41 Given all of this, unfortunately I don't think it would make sense to merge this PR as it is right now

**Comment by reidliu41** [comment]
> @reidliu41 Given all of this, unfortunately I don't think it would make sense to merge this PR as it is right now

Yeah,

**Comment by reidliu41** [comment]
> @reidliu41 in the config file, instead of grouping by release/repository etc, I would like to propose the following structure:
> 
> ```
> . . .
> # Download configuration section.
> download:
>   models:
>     - repository: instructlab/merlinite-7b-lab-GGUF
>       release: main
>       filenames:
>         - merlinite-7b-lab-Q4_K_M.gguf
>     - repository: TheBloke/Mistral-7B-Instruct-v0.2-GGUF
>       release: main
>       filenames:
>         - mistral-7b-instruct-v0.2.Q5_0.gguf
>     - repository: instructlab/granite-7b-lab
>       release: main
>     - repository: docker://quay.io/ai-lab/models/granite-7b-lab
>       release: latest
> 
>  . . .
> ```
> 
> I think we should restrict the flags to be used to specify single model downloads at a time. If users need to download multiple models they should specify them as described in the config file. The flags can then also be used to override specific items in the list by matching on the repository string
> 
> how does that sound?
> 
> cc @cdoern @alinaryan @nathan-weinberg

1. Yeah, that's what I think for the structure.
2. Sorry, I not sure I understand correctly, you mean if download multiple models, user should describe it in config first, and not read from cli?
3. Based on your `a new proposal`, it might be better to move models sections from `download` to `general`?

**Comment by reidliu41** [comment]
sorry, wrong click, but ok to close.haha.

**Comment by jaideepr97** [comment]
closing pending the filing of a formal proposal for the new config structure

**Pull request closed without merging**
