### PR TITLE
Update Chunking Methods

### PR DESCRIPTION
**Pull request by PalmPalm7**
### Demonstrated new chunking methods in replace of RecursiveCharacterTextSplitter() 

1. Resolve **chunking documents for knowledge**
2. Demonstrated three different ways of chunking.

### CODE REVIEW

**Comment by aakankshaduggal** [comment]
Resolves https://github.com/instructlab/sdg/issues/34

**Review by russellb — CHANGES_REQUESTED** [review]
It looks like this just has a jupyter notebook? Were you also working on integrating this sample code into the SDG library?

**Comment by PalmPalm7** [comment]
> It looks like this just has a jupyter notebook? Were you also working on integrating this sample code into the SDG library?

@russellb Hi Rus, I have now managed to update the chunk_document() function. Previous commit was to upload the demo. Notable updates:

1. Used a[ efficient library](https://github.com/google/magika/tree/main) to detect file type.
2. Applied document-specific test splitter from Langchain in replace of original naive version
3. Made heuristics changes to markdown file, especially using regex to trim markdown tables in attempt to fit in the whole table with limited context window.

**Comment by russellb** [comment]
Thanks. I'd actually like to do this over in the SDG repo.  See this PR: https://github.com/instructlab/sdg/pull/35

once that's merged the code will be in that repo instead

**Comment by russellb** [comment]
> Thanks. I'd actually like to do this over in the SDG repo. See this PR: [instructlab/sdg#35](https://github.com/instructlab/sdg/pull/35)
> 
> once that's merged the code will be in that repo instead

That code was merged. Feel free to proceed with your work in that repo. Thanks!

**Pull request closed without merging**
