### PR TITLE
llama backend fix

### PR DESCRIPTION
**Pull request by cdoern**
llama-cpp was switched to llama_cpp but only in certain parts of the codebase making it hard for users to specify the backend they want to use.

Switch all instances of llama_cpp backend type back to llama-cpp

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Functional tests have been added, if necessary.
- [ ] E2E Workflow tests have been added, if necessary.

### CODE REVIEW

**Comment by nathan-weinberg** [comment]
@cdoern @alinaryan we are sure this is inclusive of everything changed in https://github.com/instructlab/instructlab/pull/2467?

Also, we should add an additional unit test to ensure regressions like this can't happen again

**Comment by nathan-weinberg** [comment]
@Mergifyio backport release-v0.20

**Comment by cdoern** [comment]
@nathan-weinberg I dont think we need an additional unit test. The unit test to account for this was changed causing it to pass w/ the incorrect value, same could happen for any cfg entry honestly.

**Comment by cdoern** [comment]
I did the side by side comparison myself, this is the extent of the breaking changes.

**Comment by nathan-weinberg** [comment]
@cdoern we should add a test ensuring that the values are consistent - afraid I'll have to insist on this since there was a regression - this is standard practice when regressions occur - obviously the existing test was not sufficient to expose to @alinaryan what the root cause of the issue was in the first place - non-Maintainers are more even likely to make a similar change by accident

**Comment by cdoern** [comment]
added two tests

**Comment by alinaryan** [comment]
>we are sure this is inclusive of everything changed in https://github.com/instructlab/instructlab/pull/2467?

@nathan-weinberg yes I sat down and checked each change manually. this covers it

**Review by nathan-weinberg — APPROVED** [review]

**Review by alinaryan — APPROVED** [review]

**Pull request merged**
