### PR TITLE
Expand env vars and user dirs read from config

### PR DESCRIPTION
**Pull request by danmcp**
Expands env vars (Ex: $HOME) and user vars (Ex: ~) for config and training profiles.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [x] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by n1hility — APPROVED** [review]
Also tested in image

**Review by nathan-weinberg — APPROVED** [review]

**Comment by RobotSail** [comment]
It seems like this PR introduced some circular import issues that I'm now experiencing when adding new code paths into the designated files. For reference, see the failure in this CI runner:

https://github.com/instructlab/instructlab/actions/runs/10285276171/job/28463143941#step:11:57

**Comment by nathan-weinberg** [comment]
How did this not fail on the PR checks here?

**Comment by bjhargrave** [comment]
Perhaps this is an interaction of multiple PRs which landed near the same time?

**Comment by RobotSail** [comment]
@bjhargrave @nathan-weinberg This seems to be an issue only when we move code into utils which imports from ilabclient - since that's what the breaking PR is doing. 

This PR is perfectly fine and doing the right thing, it just seems like this is a very Python-specific issue since we need to interpret all of our paths. 

The better solution to this issue would be to move all of the defaults into a dedicated file, and that way we wouldn't have any of these circular dependency problems.

**Pull request merged**
