### PR TITLE
fix optional_dependencies key not matching python-identifier format

### PR DESCRIPTION
**Pull request by booxter**
Related-Bug: https://github.com/instructlab/instructlab/issues/1464

### CODE REVIEW

**Review by nathan-weinberg — APPROVED** [review]

**Review by bjhargrave — APPROVED** [review]

**Comment by tiran** [comment]
According to https://packaging.python.org/en/latest/specifications/dependency-specifiers/ `vllm-cuda` is a valid specifier. You may have to quote the string as `optional-dependencies."vllm-cuda"` in TOML.

**Review by tiran — CHANGES_REQUESTED** [review]
`vllm-cuda` extra requires is fine and works for me.

According to https://packaging.python.org/en/latest/specifications/dependency-specifiers/, the `-` is a supported character:
```
identifier_end = letterOrDigit | (('-' | '_' | '.' )* letterOrDigit)
identifier    = letterOrDigit identifier_end*
name          = identifier
```

`pip install --dry-run .[vllm-cuda]` on latest main works for me and attempts to install the correct packages:
```
Would install GitPython-3.1.43 Jinja2-3.1.4 MarkupSafe-2.1.5 PyYAML-6.0.1 Pygments-2.18.0 absl-py-2.1.0 accelerate-0.31.0 aiofiles-24.1.0 aiohttp-3.9.5 aiosignal-1.3.1 annotated-types-0.7.0 anyio-4.4.0 attrs-23.2.0 certifi-2024.6.2 charset-normalizer-3.3.2 click-8.1.7 click-didyoumean-0.3.1 cloudpickle-3.0.0 cmake-3.29.6 datasets-2.20.0 deepspeed-0.14.4 dill-0.3.8 diskcache-5.6.3 distro-1.9.0 dnspython-2.6.1 docker-pycreds-0.4.0 docstring_parser-0.16 email_validator-2.2.0 fastapi-0.111.0 fastapi-cli-0.0.4 filelock-3.15.4 frozenlist-1.4.1 fsspec-2024.5.0 gguf-0.6.0 gitdb-4.0.11 h11-0.14.0 hjson-3.1.0 httpcore-1.0.5 httptools-0.6.1 httpx-0.27.0 huggingface-hub-0.23.4 idna-3.7 importlib_metadata-8.0.0 instructlab-0.17.1.dev122 instructlab-dolomite-0.0.1 instructlab-quantize-0.1.0 instructlab-schema-0.2.0 instructlab-sdg-0.0.4 instructlab-training-0.0.3 interegular-0.3.3 joblib-1.4.2 jsonpatch-1.33 jsonpointer-3.0.0 jsonschema-4.22.0 jsonschema-specifications-2023.12.1 langchain-core-0.2.10 langchain-text-splitters-0.2.2 langsmith-0.1.82 lark-1.1.9 llama_cpp_python-0.2.75 llvmlite-0.43.0 lm-format-enforcer-0.10.1 markdown-it-py-3.0.0 mdurl-0.1.2 mpmath-1.3.0 msgpack-1.0.8 multidict-6.0.5 multiprocess-0.70.16 nest-asyncio-1.6.0 networkx-3.3 ninja-1.11.1.1 nltk-3.8.1 numba-0.60.0 numpy-1.26.4 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-ml-py-12.555.43 nvidia-ml-py3-7.352.0 nvidia-nccl-cu12-2.20.5 nvidia-nvjitlink-cu12-12.5.40 nvidia-nvtx-cu12-12.1.105 openai-1.35.5 orjson-3.10.5 outlines-0.0.46 packaging-24.1 pandas-2.2.2 pathspec-0.12.1 peft-0.11.1 pillow-10.3.0 platformdirs-4.2.2 prometheus-fastapi-instrumentator-7.0.0 prometheus_client-0.20.0 prompt_toolkit-3.0.47 protobuf-5.27.2 psutil-6.0.0 py-cpuinfo-9.0.0 pyairports-2.1.1 pyarrow-16.1.0 pyarrow-hotfix-0.6 pycountry-24.6.1 pydantic-2.7.4 pydantic-settings-2.3.4 pydantic_core-2.18.4 pydantic_yaml-1.3.0 python-dateutil-2.9.0.post0 python-dotenv-1.0.1 python-multipart-0.0.9 pytz-2024.1 ray-2.31.0 referencing-0.35.1 regex-2024.5.15 requests-2.32.3 rich-13.7.1 rouge_score-0.1.2 rpds-py-0.18.1 ruamel.yaml-0.18.6 ruamel.yaml.clib-0.2.8 safetensors-0.4.3 sentencepiece-0.2.0 sentry-sdk-2.7.0 setproctitle-1.3.3 shellingham-1.5.4 shtab-1.7.1 six-1.16.0 smmap-5.0.1 sniffio-1.3.1 sse-starlette-2.1.2 starlette-0.37.2 starlette-context-0.3.6 sympy-1.12.1 tenacity-8.4.2 tiktoken-0.7.0 tokenizers-0.19.1 toml-0.10.2 torch-2.3.0 tqdm-4.66.4 transformers-4.41.2 triton-2.3.0 trl-0.9.4 typer-0.12.3 typing_extensions-4.12.2 tyro-0.8.5 tzdata-2024.1 ujson-5.10.0 urllib3-2.2.2 uvicorn-0.30.1 uvloop-0.19.0 vllm-0.5.0.post1 vllm-flash-attn-2.5.9 wandb-0.17.3 watchfiles-0.22.0 wcwidth-0.2.13 websockets-12.0 xformers-0.0.26.post1 xxhash-3.4.1 yamllint-1.35.1 yarl-1.9.4 zipp-3.19.2
```

Are you maybe using an outdated pip version? We only support the latest versions.

**Comment by booxter** [comment]
@tiran 

This did the job: `pip install --user --upgrade virtualenv` (20.21.10->20.26.3).

```
$ tox -e mypy
pkg: _optional_hooks> python /usr/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
pkg: get_requires_for_build_wheel> python /usr/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
mypy: packaging backend failed (code=1), with ValueError: invalid pyproject.toml config: `tool.setuptools.dynamic.optional-dependencies`.
configuration error: `tool.setuptools.dynamic.optional-dependencies` keys must be named by:

    {format: 'python-identifier'}

/home/vagrant/git/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
  warnings.warn(msg, _BetaConfiguration)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pyproject_api/_backend.py", line 90, in run
    outcome = backend_proxy(parsed_message["cmd"], **parsed_message["kwargs"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyproject_api/_backend.py", line 32, in __call__
    return getattr(on_object, name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/git/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/git/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
    self.run_setup()
  File "/home/vagrant/git/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 1, in <module>
  File "/home/vagrant/git/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/git/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 159, in setup
    dist.parse_config_files()
  File "/home/vagrant/git/instructlab/.tox/pkg/lib/python3.11/site-packages/_virtualenv.py", line 21, in parse_config_files
    result = old_parse_config_files(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/git/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/dist.py", line 868, in parse_config_files
    pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
  File "/home/vagrant/git/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 62, in apply_configuration
    config = read_configuration(filepath, True, ignore_option_errors, dist)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/git/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 126, in read_configuration
    validate(subset, filepath)
  File "/home/vagrant/git/instructlab/.tox/pkg/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 51, in validate
    raise ValueError(f"{error}\n{summary}") from None
ValueError: invalid pyproject.toml config: `tool.setuptools.dynamic.optional-dependencies`.
configuration error: `tool.setuptools.dynamic.optional-dependencies` keys must be named by:

    {format: 'python-identifier'}

Backend: run command get_requires_for_build_wheel with args {'config_settings': None}
configuration error: `tool.setuptools.dynamic.optional-dependencies` keys must be named by:

    {format: 'python-identifier'}

GIVEN VALUE:
    {
        "hpu": {
            "file": [
                "requirements-hpu.txt"
            ]
        },
        "vllm-cuda": {
            "file": [
                "requirements-vllm-cuda.txt"
            ]
        }
    }

OFFENDING RULE: 'propertyNames'

DEFINITION:
    {
        "type": "object",
        "propertyNames": {
            "format": "python-identifier"
        },
        "additionalProperties": false,
        "patternProperties": {
            ".+": {
                "$id": "#/definitions/file-directive",
                "title": "'file:' directive",
                "description": "Value is read from a file (or list of files and then concatenated)",
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "file": {
                        "oneOf": [
                            {
                                "type": "string"
                            },
                            {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        ]
                    }
                },
                "required": [
                    "file"
                ]
            }
        }
    }
Backend: Wrote response {'code': 1, 'exc_type': 'ValueError', 'exc_msg': "invalid pyproject.toml config: `tool.setuptools.dynamic.optional-dependencies`.\nconfiguration error: `tool.setuptools.dynamic.optional-dependencies` keys must be named by:\n\n    {format: 'python-identifier'}\n"} to /tmp/pep517_get_requires_for_build_wheel-8xvoihzq.json
  mypy: FAIL code 1 (0.86 seconds)
  evaluation failed :( (0.94 seconds)
$ .tox/mypy/bin/pip --version
pip 24.1.1 from /home/vagrant/git/instructlab/.tox/mypy/lib/python3.11/site-packages/pip (python 3.11)
$ .tox/mypy/bin/python --version
Python 3.11.9
$ vim tox.ini
$ tox --version
4.14.2 from /usr/lib/python3.11/site-packages/tox/__init__.py
$ pip install --user --upgrade virtualenv
Requirement already satisfied: virtualenv in /usr/lib/python3.11/site-packages (20.21.1)
Collecting virtualenv
  Using cached virtualenv-20.26.3-py3-none-any.whl (5.7 MB)
Requirement already satisfied: distlib<1,>=0.3.7 in /home/vagrant/.local/lib/python3.11/site-packages (from virtualenv) (0.3.8)
Requirement already satisfied: filelock<4,>=3.12.2 in /home/vagrant/.local/lib/python3.11/site-packages (from virtualenv) (3.15.4)
Requirement already satisfied: platformdirs<5,>=3.9.1 in /home/vagrant/.local/lib/python3.11/site-packages (from virtualenv) (4.2.2)
$ tox -r -e mypy
mypy: remove tox env folder /home/vagrant/git/instructlab/.tox/mypy
.pkg: remove tox env folder /home/vagrant/git/instructlab/.tox/.pkg
pkg: remove tox env folder /home/vagrant/git/instructlab/.tox/pkg
mypy: install_deps> python -I -m pip install 'mypy<2.0,>=1.10.0' pytest types-PyYAML types-tqdm
pkg: install_requires> python -I -m pip install 'setuptools>=64' 'setuptools_scm>=8'
pkg: _optional_hooks> python /usr/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
pkg: get_requires_for_build_wheel> python /usr/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
pkg: build_wheel> python /usr/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
...
```

**Comment by tiran** [comment]
You are somehow running an older setuptools. The optional dependency format is `pep508-identifier`, not `python-identifier`.

**Comment by tiran** [comment]
Which setuptools version is installed in `.tox/pkg` ? Do we need to bump the minimal setuptools version in `pyproject.toml` to a more recent version?

**Comment by booxter** [comment]
@tiran I've upgraded the environment and no longer have the issue. Clearly, it was something about an older version of virtualenv or setuptools (these got bumped for me when I installed a newer tox - but the older tox would also works once virtualenv was upgraded). I don't think this patch is needed after all. Thanks for blocking it.

**Comment by tiran** [comment]
For the record, the issue was fixed in commit 030ba3a091c7257b42ab0819aae1bec7b9f3d255 . InstructLab now requires a more recent setuptools version that is not affected by the bug.

**Pull request closed without merging**
