### PR TITLE
validate the safetensors file

### PR DESCRIPTION
**Pull request by reidliu41**
enhance `is_model_safetensors`,  add the check for `safetensors` file

```
 ls -lh *test_model.safetensors
-rw-r--r--  1 xx  xx    16B Oct 10 23:02 empty_tensors_test_model.safetensors
-rw-r--r--  1 xx  xx   184B Oct 10 23:02 test_model.safetensors
-rw-r--r--  1 xx  xx     0B Oct 10 23:07 empty_test_model.safetensors

$ ilab -v model list
DEBUG 2024-10-10 23:03:11,117 instructlab.model.backends.backends:48: No tensors found in /Users/xx/.cache/instructlab/models/instructlab/granite-7b-lab/empty_tensors_test_model.safetensors

DEBUG 2024-10-10 23:12:39,357 instructlab.model.backends.backends:52: Error while processing /Users/xx/.cache/instructlab/models/instructlab/granite-7b-lab/empty_test_model.safetensors: Error while deserializing header: HeaderTooSmall

```

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Functional tests have been added, if necessary.
- [ ] E2E Workflow tests have been added, if necessary.

### CODE REVIEW

**Comment by jaideepr97** [comment]
Thanks for the PR @reidliu41, this is great! I've felt for a while that we needed a stronger check for safetensors files 
Could you look at the failing unit test?

**Comment by reidliu41** [comment]
> Thanks for the PR @reidliu41, this is great! I've felt for a while that we needed a stronger check for safetensors files Could you look at the failing unit test?

thanks for reply, fixed it

**Review by jaideepr97 — APPROVED** [review]
LGTM thanks @reidliu41 !

**Comment by reidliu41** [comment]
hi guys, please feel free to share ideas.

**Review by markstur — APPROVED** [review]
lgtm, thanks!

**Comment by nathan-weinberg** [comment]
This PR predates some recent Mergify changes, thus no automerge - merging manually

**Pull request merged**
