### PR TITLE
mergify: Fix config for changes to github workflows

### PR DESCRIPTION
**Pull request by russellb**
commit 50b1799d725aaca21d651572512f34fa4fd31cf3
Author: Russell Bryant <rbryant@redhat.com>
Date:   Fri Apr 26 12:39:38 2024 -0400

    mergify: Don't require lint & test on github config changes
    
    The previous config was excpecting the lint and test jobs to run and
    pass on PRs taht only changed files under `.github/`, but those PRs
    won't run those jobs.
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

### CODE REVIEW

**Comment by nathan-weinberg** [comment]
@russellb one nit: can you update the labeler config to include mergify config changes to get the `CI/CD` label

**Comment by nathan-weinberg** [comment]
Config is here: https://github.com/instructlab/instructlab/blob/main/.github/labeler.yml#L6

**Comment by russellb** [comment]
> @russellb one nit: can you update the labeler config to include mergify config changes to get the `CI/CD` label

done

**Comment by russellb** [comment]
I'm manually merging this, as mergify does not auto-merge changes to its configuration.

**Pull request merged**
