### PR TITLE
Define a relaxed schema as v1 and move current schema to v2

### LINKED ISSUE #989: `ilab generate` fails with schema errors when used with existing skills in the instructlab/taxonomy repo
We validate the yaml files match our linting rules (line length, required attribution, etc) during `ilab generate`. Some of the merged skills and knowledge in the instructlab/taxonomy repository were merged before all of the linting was in place, and are not valid by today's standards. We need some way to tell `ilab generate` to ignore yaml validation errors or some versioning in place between the schema, CLI, and taxonomy files so that each change to our linting rules is a new schema version and we can properly handle older taxonomy files done with looser linting compared to newer taxonomy files with different linting rules.

Example of the error I get today pointing the CLI at some existing knowledge in the merged taxonomy repo:

```
$ ilab generate --taxonomy-path taxonomy/knowledge/textbook/history/ibm_history/qna.yaml
...
INFO 2024-04-24 18:12:31,333 _client.py:1026 HTTP Request: GET http://127.0.0.1:8000/v1/models "HTTP/1.1 200 OK"
Generating synthetic data using 'merlinite-7b-lab-Q4_K_M' model, taxonomy:'taxonomy/knowledge/textbook/history/ibm_history/qna.yaml' against http://127.0.0.1:8000/v1 server
ERROR 2024-04-24 18:12:31,421 utils.py:462 Problems found in file taxonomy/knowledge/textbook/history/ibm_history/qna.yaml
36:121: [warning] line too long (314 > 120 characters) (line-length)
39:121: [warning] line too long (363 > 120 characters) (line-length)
42:121: [warning] line too long (410 > 120 characters) (line-length)
```

### PR DESCRIPTION
**Pull request by bjhargrave**
# Changes

**Which issue is resolved by this Pull Request:**
Resolves #989

**Description of your changes:**

We introduce a relaxed schema as v1 which will accept all existing
taxonomy files in the main branch of the taxonomy repo. The current
v1 schema is renamed to v2 and will be used for future contributions
to the taxonomy repo.

Fixes https://github.com/instructlab/instructlab/issues/989

Depends on https://github.com/instructlab/instructlab/pull/913
and https://github.com/instructlab/schema/pull/11

### CODE REVIEW

**Comment by bjhargrave** [comment]
This PR will need rebasing once #913 and https://github.com/instructlab/schema/pull/11 are merged.

**Comment by russellb** [comment]
@bjhargrave can you clarify the `hold` on this? Was it just so #913 goes in first?

**Comment by bjhargrave** [comment]
> can you clarify the `hold` on this? Was it just so #913 goes in first?

#913 is now merged. But we also need to merge https://github.com/instructlab/schema/pull/11 before this PR. I did not merge the schema PR until we agreed to this overall schema v1/v2 concept in the cli.

**Comment by bjhargrave** [comment]
@russellb It would be nice to get a review on this since the issue addressed by this PR is in the 5/2 milestone.

**Review by russellb — APPROVED** [review]

**Pull request merged**
