### PR TITLE
fix: medium e2e bug where generate points to repo not model

### PR DESCRIPTION
**Pull request by nathan-weinberg**
**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Functional tests have been added, if necessary.
- [ ] E2E Workflow tests have been added, if necessary.

### CODE REVIEW

**Review by cdoern — APPROVED** [review]
Sorry didn't catch this in the last one

**Comment by nathan-weinberg** [comment]
> Sorry didn't catch this in the last one

No worries - if the test succeeds on the PR we'll know it's gtg

**Review by alinaryan — APPROVED** [review]

**Comment by cdoern** [comment]
hmmmmmmm. I think `full` SDG might not generate MMLU Branch task dir files if its only generating skills. This makes sense, but means we can't test MMLU Branch on the medium job.

@nathan-weinberg I will leave this for you tomorrow to decide if thats ok w/ you. If it is, the solution is to disable MMLU branch on this job

**Comment by nathan-weinberg** [comment]
> hmmmmmmm. I think `full` SDG might not generate MMLU Branch task dir files if its only generating skills. This makes sense, but means we can't test MMLU Branch on the medium job.
> 
> @nathan-weinberg I will leave this for you tomorrow to decide if thats ok w/ you. If it is, the solution is to disable MMLU branch on this job

Yeah no worries I'll remove the commit tomorrow

**Pull request merged**
