### PR TITLE
Standardized on the Fancy GitHub callouts

### PR DESCRIPTION
**Pull request by jjasghar**
I updated the formatting to get the "fancy" callouts standard through the readme. I had to change some of the other formatting around, too, to make it consistent.

### CODE REVIEW

**Review by leseb — COMMENTED** [review]
In the future, could you use your own fork instead of pushing branches directly to instructlab/instructlab? We'd like to only display "release-v" branches to the community and avoid showing any working branches. Thanks!

**Comment by nathan-weinberg** [comment]
Spellcheck needs fixing (and also I agree with what @leseb said above) otherwise this is a welcome change! Thanks @jjasghar! Will approve once CI is fixed

**Review by kelbrown20 — COMMENTED** [review]
All the updates look good to me! Just need the rebase and spell check fixes

**Comment by nathan-weinberg** [comment]
This is seemingly abandoned and out-of-sync with the current README, closing this

**Pull request closed without merging**
