### PR TITLE
introduce backends.common to reduce circular dependencies

### PR DESCRIPTION
**Pull request by makelinux**
The backends module and modules llama_cpp and vllm have circular dependency, which is anti-pattern.

The backends module, along with the llama_cpp and vllm modules, have a circular dependencies, which is considered an anti-pattern."
    
This PR is intentionally kept small to facilitate an easier code review. The plan is to relocate the relevant code from `backends` to `common` in a subsequent PR, eliminating the circular dependency entirely.

Current state:
```mermaid
graph LR;
  backends --> llama_cpp
  llama_cpp --> backends
  backends --> vllm
  vllm --> backends
```
Desired state:

```mermaid
graph LR;
  backends --> llama_cpp
  llama_cpp -->common
  backends --> common
  backends --> vllm
  vllm --> common
```

References:
1. https://en.wikipedia.org/wiki/Circular_dependency
2. https://en.wikipedia.org/wiki/Acyclic_dependencies_principle

### CODE REVIEW

**Comment by khaledsulayman** [comment]
@makelinux could you link the follow-up PR if it's ready? Might be better to merge these 2 in succession.

**Review by leseb — APPROVED** [review]

**Comment by makelinux** [comment]
> @makelinux could you link the follow-up PR if it's ready? Might be better to merge these 2 in succession.
@khaledsulayman,

Unfortunately, it's not practical to submit several commits or pull requests simultaneously. Combining multiple changes in a single pull request increases the risk of merge conflicts and may require multiple rebases. Creating a pull request based on another is also challenging, if not impossible. If you have any suggestions or know of a workaround, please let me know.

**Review by RobotSail — APPROVED** [review]
LGTM

**Review by markstur — APPROVED** [review]
lgtm
Thanks!

**Pull request merged**
