### PR TITLE
Eval E2E test using trained model

### PR DESCRIPTION
**Pull request by cdoern**
enable eval on the a10x4, swap in trained model
    
 this enables eval to run using the last checkpoint from training. It also enables this workflow to run on the a10x4 runners

### CODE REVIEW

**Comment by cdoern** [comment]
this is built on top of #1676

**Comment by mairin** [comment]
This is proposed as a blocker. What's the consequence on 0.18.0 if this doesn't make it in?

**Comment by cdoern** [comment]
@mairin this is not really  a functional blocker as we have validated evaluations functionality manually. I'm fine with removing this from the blocker list!

**Comment by mairin** [comment]
@cdoern OK cool, thanks! If this doesn't make it in we won't have eval tests of the trained model in CI, right?

**Comment by nathan-weinberg** [comment]
@mairin that's correct - @cdoern i can help you try and get this over the line but we can prioritize appropriately (i.e. not hold a 0.18.0 release for this)

**Comment by mairin** [comment]
This is not a blocker, it can make it into 0.18.0 if ready because it's CI and does not impact code.

**Comment by alinaryan** [comment]
Blocked on testing. There is not enough capacity in the a10x4 ci test

**Comment by nathan-weinberg** [comment]
> Blocked on testing. There is not enough capacity in the a10x4 ci test

Is it because of the size of the Prometheus model? We could use something like Merlinite instead since we're not as concerned with results here (if that's the issue)

**Comment by ktam3** [comment]
Closing this in favor of #1642

**Pull request closed without merging**
