### PR TITLE
python version bump

### PR DESCRIPTION
**Pull request by cdoern**
dolomite does not have python 3.9 support. Remove 3.9 tests and edit docs, pyproject, etc.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by russellb — APPROVED** [review]
lgtm -- 3.10 is the minimum I am aware of that we need to support.

I would suggest expanding your commit message and PR description a bit more to clarify where this is coming from.  You can link to this repo, which is where we are publishing `instructlab-dolomite` from -- https://github.com/instructlab/GPTDolomite

**Review by RobotSail — APPROVED** [review]
LGTM - it would be nice if we could get dolomite to support 3.9 eventually but it's not a high priority.

**Comment by bjhargrave** [comment]
Shouldn't this be mentioned in CHANGELOG as it raises the floor on python versions supported? People using python 3.9 will be surprised when they update ilab and find it may not work.

It seems like this change should be widely communicated.

**Comment by nathan-weinberg** [comment]
> Shouldn't this be mentioned in CHANGELOG as it raises the floor on python versions supported? People using python 3.9 will be surprised when they update ilab and find it may not work.
> 
> It seems like this change should be widely communicated.

+1, I raised this exact point in Slack...

**Comment by russellb** [comment]
good point re: ChangeLog. Can someone suggest an addition in a PR?

**Pull request merged**
